/*!
 * Author: imqiqiboy@gmail.com
 * Date: 2014-12-26 18:57:21
 *
 * include "createClass.js"
 * include "animation.js"
 * include "jpromise.js"
 * include "sketch.js"
 * include "zepto.min.js"
 * include "common.js"
 */
!function(a,d,e){function n(a,b){for(var k=0,c=a.length,l=[],d;k<c;k++)"undefined"!==typeof(d=b(a[k]))&&l.push(d);return l}function q(){var a=arguments.length-1,b=arguments[a],k=arguments[0]||{},c=typeof k,l=1,d,e;"boolean"!==typeof b&&(b=!1,a++);for("object"!=c&&"function"!=c&&(k={});l<a;l++)if(null!=(c=arguments[l]))for(d in c)e=k[d],copy=c[d],k!==copy&&(k[d]=b&&"object"==typeof copy&&null!=copy?q("object"==typeof e&&null!=e?e:"[object Array]"=={}.toString.call(copy)?[]:{},copy,b):copy);return k}
function c(a,b){var k="function"==typeof a;return k==("function"==typeof b)?0:k?-1:1}function k(){}var l=a[d]=function(){function a(b){h.apply(this,b)}function b(){return new a(arguments)}var h=arguments[0],d=[].slice.call(arguments,"function"==typeof h&&!function(a){for(a in h.prototype)return!0}()?1:(h=k,0)),r=[],e={_self:h,_super:function(){r[0]&&(r[0].prototype._self||r[0]).apply(this,arguments)},extend:function(){var a=this;return q.apply(null,(this===e?[]:[this]).concat(n([{constructor:b}].concat([].slice.call(arguments,
0),e).sort(c),function(b){"function"==typeof b&&!a.isInstanceof(b)&&r.push(b);"function"==typeof b&&(k.prototype=b.prototype,b=new k);return b})))},isInstanceof:function(a){var b;if(!(b=this instanceof a))a:{for(var k=0,c=r.length;k<c;k++)if(b=r[k].prototype.isInstanceof,r[k]===a||b&&b.call(this,a)){b=!0;break a}b=!1}return b}};a.prototype=b.fn=b.prototype=e.extend.apply(e,d);b.extend=function(){return l.apply(null,[].slice.call(arguments,0).concat(this))};return b}}(window,"createClass");(function(a,d,e){var n=0,q=a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.msRequestAnimationFrame||function(a){var c=d.prototype.now(),q=Math.max(1E3/60,1E3/60-(c-n));n=c+q;return setTimeout(a,q)},c=a.cancelAnimationFrame||a.webkitCancelAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||clearTimeout;"function"!=typeof Function.prototype.bind&&(Function.prototype.bind=function(a){var c=this;
return function(){return c.apply(a,arguments)}});"function"!=typeof Array.prototype.forEach&&(Array.prototype.forEach=function(a){for(var c=0,d=this.length,b;c<d;c++)b=this[c],"undefined"!=typeof b&&a(b,c,this)});d.prototype={constructor:d,playing:!1,complete:!1,percent:0,bindEvent:function(){this.events={};this.finish(function(){this.complete=!0})},on:function(a,c){if("object"==typeof a)for(var d in a)this.on(d,a[d]);else this.events[a]||(this.events[a]=[]),this.events[a].push(c);return this},fire:function(a){var c=
[].slice.call(arguments,1);(this.events[a]||[]).forEach(function(a){"function"==typeof a&&a.apply(this,c)}.bind(this));return this},now:Date.now||function(){return+new Date},toggle:function(){return this.playing?this.stop():this.start()},reset:function(){this.timeout=0;return this.next()},_start:function(){this.playing||(this.playing=!0,this.tweenTime=this.now(),this.complete&&(this.complete=!1,this.timeout=0),this.fire("start").next());return this},_next:function(){var a=this.duration,l=this.now(),
d=this.playing?l-this.tweenTime:0;this.percent=a?this.easeFunc.call(null,this.timeout=Math.max(0,Math.min(a,this.timeout+d)),0,a,a)/a:1;this.tweenTime=l;this.fire("next",this.frameTime=d);this.timeout<a?(c(this._timer),this.playing&&(this._timer=q(this.next.bind(this)))):this.stop().fire("finish");return this},_stop:function(){this.playing&&(this.playing=!1,c(this._timer),this.fire("stop"));return this},_finish:function(){this.complete||(this.timeout=this.duration,this.next());return this},frame:function(a,
c){var d="function"==typeof a,b=0,h=0;return this.next(function(){var q=d?a.call(this):a;b+=this.frameTime;b>=q&&(b%=q,c.call(this,(b-h)/q),h=b)})},setDuration:function(a){this.timeout=(this.duration?this.timeout/this.duration:0)*(this.duration=parseFloat(a)||0);return this},setTween:function(a){this.easeFunc="function"==typeof a?a:function(a,c,b,k){return b*a/k+c};return this}};["start","next","stop","finish"].forEach(function(a){d.prototype[a]=function(c){return"function"==typeof c?this.on(a,c):
this["_"+a]()}});a.Animation=d})(window,function(a,d){if(!(this instanceof arguments.callee))return new arguments.callee(a,d);this.setDuration(a).setTween(d).bindEvent()});(function(a,d,e){"function"!=typeof Function.prototype.bind&&(Function.prototype.bind=function(a){var c=this;return function(){return c.apply(a,arguments)}});"function"!=typeof Array.prototype.forEach&&(Array.prototype.forEach=function(a){for(var c=0,d=this.length,b;c<d;c++)b=this[c],"undefined"!=typeof b&&a(b,c,this)});var n={resolved:"resolve",rejected:"reject",pending:"notify"},q=[].slice,c={}.toString;d.prototype={constructor:d,state:"pending",on:function(a,c){this.handles[a]||(this.handles[a]=
[]);"function"==typeof c&&this.handles[a].push(c);return this},fire:function(a){var c=this.args||[],d=this.handles[a]||[];if("notify"==a)d.forEach(function(a){a.apply(null,c)});else for(;d.length;)d.shift().apply(null,c);return this},then:function(){var a=new d,c=arguments;["resolve","reject","notify"].forEach(function(d,b){this.on(d,function(){var h=q.call(arguments),m;if("function"==typeof c[b]){try{m=c[b].apply(null,h),1==b&&(d="resolve")}catch(r){d="reject",m=r}h=[m]}a[d].apply(a,h)})}.bind(this));
switch(this.state){case "resolved":case "rejected":this.fire(n[this.state])}return a},chain:function(a){return this.then(function(){a.resolve.apply(a,arguments)},function(){a.reject.apply(a,arguments)},function(){a.notify.apply(a,arguments)})},delay:function(a){return this.always(function(){var c=arguments;return d(function(d){setTimeout(function(){d.apply(null,c)},a)})})},"catch":function(a){return this.then(null,a)},done:function(a){return this.then(a)},fail:function(a){return this.then(null,a)},
always:function(a){return this.then(a,a)},progress:function(a){return this.then(null,null,a)},deferred:function(){return this},promise:function(){var a=this,c={};["then","catch","progress"].forEach(function(d){c[d]=function(){return a[d].apply(a,arguments).promise()}});return c}};["defer","promise"].forEach(function(a){d[a]=function x(b){if(this instanceof x)throw new TypeError(a+" is not a constructor");return this(b)[a]()}});["resolved","rejected","pending"].forEach(function(a){var c=n[a];d[c]=
function(){var a=new this;return a[c].apply(a,arguments)};d.prototype[c]=function(d){"pending"==this.state&&("function"==typeof(d&&d.then)?this.chain.call(d,this):(this.state=a,this.args=q.call(arguments),this.fire(c)));return this}});"when all every any some race".split(" ").forEach(function(a){var l=d[a]=function(){var e=q.call(arguments),b=[],h=[],m=e.length,r=0;return d(function(n,B,u){e.length?e.forEach(function(e,p){var f="[object Array]"==c.call(e),x,A;f?e=l.apply(null,e).progress(u):e.always(u);
e=d.resolve(e);switch(a){case "any":x=n;A=function(a){h[p]=f?q.call(arguments):a;m==++r&&B.apply(null,h)};break;case "some":x=function(a){b.push(f?q.call(arguments):a);m==++r&&n.apply(null,b)};A=function(a){h.push(f?q.call(arguments):a);m==++r&&(b.length?n.apply(null,b):B.apply(null,h))};break;case "race":x=A=n;break;default:x=function(a){b[p]=f?q.call(arguments):a;m==++r&&n.apply(null,b)},A=B}e.then(x,A)}):n()})};d.prototype[a]=function(){return l.apply(null,arguments).chain(this)}});a.JPromise=
d})(window,function(a){if(!(this instanceof arguments.callee))return new arguments.callee(a);this.handles={};"function"==typeof a&&a(this.resolve.bind(this),this.reject.bind(this),this.notify.bind(this))});(function(a,d,e){"function"!=typeof Function.prototype.bind&&(Function.prototype.bind=function(a){var c=this;return function(){return c.apply(a,arguments)}});var n="PointerEvent"in a?"pointerdown pointermove pointerup pointercancel":"createTouch"in a.document||"ontouchstart"in a?"touchstart touchmove touchend touchcancel":"mousedown mousemove mouseup";d.prototype={constructor:d,lineWidth:5,color:"#000",erase:!1,bgcolor:"transparent",init:function(a){this.events={};this.actions=[];this.ctx=this.canvas.getContext("2d");
"object"==typeof a&&["width","height","lineWidth","color","bgcolor"].forEach(function(c){this[c]="undefined"==typeof a[c]?this[c]:a[c]}.bind(this));n.split(" ").forEach(function(a){this.canvas.addEventListener(a,this,!1)}.bind(this));this.on({start:function(){this.actions.push({width:this.lineWidth,color:this.color,erase:this.erase,pens:[arguments]})},move:function(){var a=this.actions[this.steps-1];a.pens.push(arguments);this.draw({width:a.width,color:a.color,erase:a.erase,pens:a.pens.slice(-2)})},
end:function(){2>this.actions[this.steps-1].pens.length&&this.actions.pop()},redraw:function(){var a=this.ctx;"transparent"!=this.bgcolor&&(a.fillStyle=this.bgcolor,a.fillRect(0,0,this.width,this.height))}})},handleEvent:function(a){var c=a.clientX||0,d=a.clientY||0,e=this.canvas.getBoundingClientRect();if(a.touches&&a.touches.length){if(1<a.touches.length)return;c=a.touches.item(0).clientX;d=a.touches.item(0).clientY}c-=e.left;d-=e.top;c*=this.width/e.width;d*=this.height/e.height;switch(a.type.toLowerCase()){case "mousedown":case "touchstart":case "pointerdown":this.moving=
!0;this.fire("start",c,d);break;case "mousemove":case "touchmove":case "pointermove":this.moving&&(a.preventDefault(),this.fire("move",c,d));break;case "mouseup":case "touchend":case "touchcancel":case "pointerup":case "pointercancel":this.moving&&(delete this.moving,this.fire("end"))}},on:function(a,c){if("object"==typeof a)return Object.keys(a).forEach(function(c){this.on(c,a[c])}.bind(this));this.events[a]||(this.events[a]=[]);this.events[a].push(c);return this},fire:function(a){var c=[].slice.call(arguments,
1);(this.events[a]||[]).forEach(function(a){"function"==typeof a&&a.apply(this,c)}.bind(this));return this},draw:function(a){var c=this.ctx;c.lineWidth=a.width;c.lineJoin=c.lineCap="round";a.erase?(c.strokeStyle="#000",c.globalCompositeOperation="destination-out"):(c.globalCompositeOperation="source-over",c.strokeStyle=a.color);c.beginPath();a.pens.forEach(function(a,d){c[d?"lineTo":"moveTo"].apply(c,a)});c.stroke();return this},reDraw:function(){this.ctx.clearRect(0,0,this.width,this.height);this.fire("redraw");
this.actions.forEach(this.draw.bind(this));return this},cancel:function(a){this.actions.splice(-(a||1));return this.reDraw()},clear:function(){this.actions.length=0;return this.reDraw()},toDataUrl:function(a){return this.canvas.toDataURL(a)},toBlob:function(){return(this.canvas.toBlob||function(d,c){if("mozGetAsFile"in this)return d(this.mozGetAsFile("blob",c));var e=this.toDataURL(c).split(","),l=a.atob(e[1]),n=new Uint8Array(l.length),b,h;b=0;for(h=n.length;b<h;b++)n[b]=l.charCodeAt(b);d(new Blob([n.buffer],
{type:c||e[0].split(/[:;]/)[1]}))}).apply(this.canvas,arguments)}};"function"==typeof Object.defineProperties&&(["width","height"].forEach(function(a){Object.defineProperty(d.prototype,a,{get:function(){return this.canvas[a]},set:function(c){this.canvas[a]=c},enumerable:!0})}),Object.defineProperty(d.prototype,"steps",{get:function(){return this.actions.length},enumerable:!0}));a.Sketch=d})(window,function(a,d){if(!(this instanceof arguments.callee))return new arguments.callee(a,d);this.canvas="string"==
typeof a?document.getElementById(a):a;this.init(d)});var Zepto=function(){function a(a){return null==a?String(a):M[S.call(a)]||"object"}function d(F){return"function"==a(F)}function e(a){return null!=a&&a==a.window}function n(a){return null!=a&&a.nodeType==a.DOCUMENT_NODE}function q(F){return"object"==a(F)}function c(a){return q(a)&&!e(a)&&Object.getPrototypeOf(a)==Object.prototype}function k(a){return D.call(a,function(a){return null!=a})}function l(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,
"$1_$2").replace(/_/g,"-").toLowerCase()}function x(a){return a in s?s[a]:s[a]=RegExp("(^|\\s)"+a+"(\\s|$)")}function b(a){return"children"in a?C.call(a.children):f.map(a.childNodes,function(a){if(1==a.nodeType)return a})}function h(a,b,g){for(p in b)g&&(c(b[p])||I(b[p]))?(c(b[p])&&!c(a[p])&&(a[p]={}),I(b[p])&&!I(a[p])&&(a[p]=[]),h(a[p],b[p],g)):b[p]!==t&&(a[p]=b[p])}function m(a,b){return null==b?f(a):f(a).filter(b)}function r(a,b,c,g){return d(b)?b.call(a,c,g):b}function z(a,b){var c=a.className||
"",g=c&&c.baseVal!==t;if(b===t)return g?c.baseVal:c;g?c.baseVal=b:a.className=b}function B(a){var b;try{return a?"true"==a||("false"==a?!1:"null"==a?null:!/^0/.test(a)&&!isNaN(b=Number(a))?b:/^[\[\{]/.test(a)?f.parseJSON(a):a):a}catch(c){return a}}function u(a,b){b(a);for(var c=0,g=a.childNodes.length;c<g;c++)u(a.childNodes[c],b)}var t,p,f,E,A=[],C=A.slice,D=A.filter,w=window.document,g={},s={},G={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},H=/^\s*<(\w+|!)[^>]*>/,
J=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,T=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,O=/^(?:body|html)$/i,v=/([A-Z])/g,U="val css html text data width height offset".split(" "),N=w.createElement("table"),P=w.createElement("tr"),Q={tr:w.createElement("tbody"),tbody:N,thead:N,tfoot:N,td:P,th:P,"*":w.createElement("div")},V=/complete|loaded|interactive/,W=/^[\w-]*$/,M={},S=M.toString,y={},K,L,R=w.createElement("div"),X={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",
maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},I=Array.isArray||function(a){return a instanceof Array};y.matches=function(a,b){if(!b||!a||1!==a.nodeType)return!1;var c=a.webkitMatchesSelector||a.mozMatchesSelector||a.oMatchesSelector||a.matchesSelector;if(c)return c.call(a,b);var g;g=a.parentNode;(c=!g)&&(g=R).appendChild(a);g=~y.qsa(g,b).indexOf(a);c&&R.removeChild(a);
return g};K=function(a){return a.replace(/-+(.)?/g,function(a,F){return F?F.toUpperCase():""})};L=function(a){return D.call(a,function(b,c){return a.indexOf(b)==c})};y.fragment=function(a,b,g){var d,s,h;J.test(a)&&(d=f(w.createElement(RegExp.$1)));d||(a.replace&&(a=a.replace(T,"<$1></$2>")),b===t&&(b=H.test(a)&&RegExp.$1),b in Q||(b="*"),h=Q[b],h.innerHTML=""+a,d=f.each(C.call(h.childNodes),function(){h.removeChild(this)}));c(g)&&(s=f(d),f.each(g,function(a,F){if(-1<U.indexOf(a))s[a](F);else s.attr(a,
F)}));return d};y.Z=function(a,b){a=a||[];a.__proto__=f.fn;a.selector=b||"";return a};y.isZ=function(a){return a instanceof y.Z};y.init=function(a,b){var c;if(a)if("string"==typeof a)if(a=a.trim(),"<"==a[0]&&H.test(a))c=y.fragment(a,RegExp.$1,b),a=null;else{if(b!==t)return f(b).find(a);c=y.qsa(w,a)}else{if(d(a))return f(w).ready(a);if(y.isZ(a))return a;if(I(a))c=k(a);else if(q(a))c=[a],a=null;else if(H.test(a))c=y.fragment(a.trim(),RegExp.$1,b),a=null;else{if(b!==t)return f(b).find(a);c=y.qsa(w,a)}}else return y.Z();
return y.Z(c,a)};f=function(a,b){return y.init(a,b)};f.extend=function(a){var b,c=C.call(arguments,1);"boolean"==typeof a&&(b=a,a=c.shift());c.forEach(function(c){h(a,c,b)});return a};y.qsa=function(a,b){var c,g="#"==b[0],d=!g&&"."==b[0],s=g||d?b.slice(1):b,h=W.test(s);return n(a)&&h&&g?(c=a.getElementById(s))?[c]:[]:1!==a.nodeType&&9!==a.nodeType?[]:C.call(h&&!g?d?a.getElementsByClassName(s):a.getElementsByTagName(b):a.querySelectorAll(b))};f.contains=w.documentElement.contains?function(a,b){return a!==
b&&a.contains(b)}:function(a,b){for(;b&&(b=b.parentNode);)if(b===a)return!0;return!1};f.type=a;f.isFunction=d;f.isWindow=e;f.isArray=I;f.isPlainObject=c;f.isEmptyObject=function(a){for(var b in a)return!1;return!0};f.inArray=function(a,b,c){return A.indexOf.call(b,a,c)};f.camelCase=K;f.trim=function(a){return null==a?"":String.prototype.trim.call(a)};f.uuid=0;f.support={};f.expr={};f.map=function(a,b){var c,g=[],d;if("number"==typeof a.length)for(d=0;d<a.length;d++)c=b(a[d],d),null!=c&&g.push(c);
else for(d in a)c=b(a[d],d),null!=c&&g.push(c);return 0<g.length?f.fn.concat.apply([],g):g};f.each=function(a,b){var c;if("number"==typeof a.length)for(c=0;c<a.length&&!1!==b.call(a[c],c,a[c]);c++);else for(c in a)if(!1===b.call(a[c],c,a[c]))break;return a};f.grep=function(a,b){return D.call(a,b)};window.JSON&&(f.parseJSON=JSON.parse);f.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,b){M["[object "+b+"]"]=b.toLowerCase()});f.fn={forEach:A.forEach,reduce:A.reduce,
push:A.push,sort:A.sort,indexOf:A.indexOf,concat:A.concat,map:function(a){return f(f.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return f(C.apply(this,arguments))},ready:function(a){V.test(w.readyState)&&w.body?a(f):w.addEventListener("DOMContentLoaded",function(){a(f)},!1);return this},get:function(a){return a===t?C.call(this):this[0<=a?a:a+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=
this.parentNode&&this.parentNode.removeChild(this)})},each:function(a){A.every.call(this,function(b,c){return!1!==a.call(b,c,b)});return this},filter:function(a){return d(a)?this.not(this.not(a)):f(D.call(this,function(b){return y.matches(b,a)}))},add:function(a,b){return f(L(this.concat(f(a,b))))},is:function(a){return 0<this.length&&y.matches(this[0],a)},not:function(a){var b=[];if(d(a)&&a.call!==t)this.each(function(c){a.call(this,c)||b.push(this)});else{var c="string"==typeof a?this.filter(a):
"number"==typeof a.length&&d(a.item)?C.call(a):f(a);this.forEach(function(a){0>c.indexOf(a)&&b.push(a)})}return f(b)},has:function(a){return this.filter(function(){return q(a)?f.contains(this,a):f(this).find(a).size()})},eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];return a&&!q(a)?a:f(a)},last:function(){var a=this[this.length-1];return a&&!q(a)?a:f(a)},find:function(a){var b=this;return a?"object"==typeof a?f(a).filter(function(){var a=this;return A.some.call(b,
function(b){return f.contains(b,a)})}):1==this.length?f(y.qsa(this[0],a)):this.map(function(){return y.qsa(this,a)}):[]},closest:function(a,b){var c=this[0],g=!1;for("object"==typeof a&&(g=f(a));c&&!(g?0<=g.indexOf(c):y.matches(c,a));)c=c!==b&&!n(c)&&c.parentNode;return f(c)},parents:function(a){for(var b=[],c=this;0<c.length;)c=f.map(c,function(a){if((a=a.parentNode)&&!n(a)&&0>b.indexOf(a))return b.push(a),a});return m(b,a)},parent:function(a){return m(L(this.pluck("parentNode")),a)},children:function(a){return m(this.map(function(){return b(this)}),
a)},contents:function(){return this.map(function(){return C.call(this.childNodes)})},siblings:function(a){return m(this.map(function(a,c){return D.call(b(c.parentNode),function(a){return a!==c})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return f.map(this,function(b){return b[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display="");if("none"==getComputedStyle(this,"").getPropertyValue("display")){var a=this.style,
b=this.nodeName,c,d;g[b]||(c=w.createElement(b),w.body.appendChild(c),d=getComputedStyle(c,"").getPropertyValue("display"),c.parentNode.removeChild(c),"none"==d&&(d="block"),g[b]=d);a.display=g[b]}})},replaceWith:function(a){return this.before(a).remove()},wrap:function(a){var b=d(a);if(this[0]&&!b)var c=f(a).get(0),g=c.parentNode||1<this.length;return this.each(function(d){f(this).wrapAll(b?a.call(this,d):g?c.cloneNode(!0):c)})},wrapAll:function(a){if(this[0]){f(this[0]).before(a=f(a));for(var b;(b=
a.children()).length;)a=b.first();f(a).append(this)}return this},wrapInner:function(a){var b=d(a);return this.each(function(c){var g=f(this),d=g.contents();c=b?a.call(this,c):a;d.length?d.wrapAll(c):g.append(c)})},unwrap:function(){this.parent().each(function(){f(this).replaceWith(f(this).children())});return this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(a){return this.each(function(){var b=f(this);
(a===t?"none"==b.css("display"):a)?b.show():b.hide()})},prev:function(a){return f(this.pluck("previousElementSibling")).filter(a||"*")},next:function(a){return f(this.pluck("nextElementSibling")).filter(a||"*")},html:function(a){return 0 in arguments?this.each(function(b){var c=this.innerHTML;f(this).empty().append(r(this,a,b,c))}):0 in this?this[0].innerHTML:null},text:function(a){return 0 in arguments?this.each(function(b){b=r(this,a,b,this.textContent);this.textContent=null==b?"":""+b}):0 in this?
this[0].textContent:null},attr:function(a,b){var c;return"string"==typeof a&&!(1 in arguments)?!this.length||1!==this[0].nodeType?t:!(c=this[0].getAttribute(a))&&a in this[0]?this[0][a]:c:this.each(function(c){if(1===this.nodeType)if(q(a))for(p in a){var g=p;c=a[p];null==c?this.removeAttribute(g):this.setAttribute(g,c)}else g=a,c=r(this,b,c,this.getAttribute(a)),null==c?this.removeAttribute(g):this.setAttribute(g,c)})},removeAttr:function(a){return this.each(function(){1===this.nodeType&&this.removeAttribute(a)})},
prop:function(a,b){a=X[a]||a;return 1 in arguments?this.each(function(c){this[a]=r(this,b,c,this[a])}):this[0]&&this[0][a]},data:function(a,b){var c="data-"+a.replace(v,"-$1").toLowerCase(),c=1 in arguments?this.attr(c,b):this.attr(c);return null!==c?B(c):t},val:function(a){return 0 in arguments?this.each(function(b){this.value=r(this,a,b,this.value)}):this[0]&&(this[0].multiple?f(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value)},offset:function(a){if(a)return this.each(function(b){var c=
f(this);b=r(this,a,b,c.offset());var g=c.offsetParent().offset();b={top:b.top-g.top,left:b.left-g.left};"static"==c.css("position")&&(b.position="relative");c.css(b)});if(!this.length)return null;var b=this[0].getBoundingClientRect();return{left:b.left+window.pageXOffset,top:b.top+window.pageYOffset,width:Math.round(b.width),height:Math.round(b.height)}},css:function(b,c){if(2>arguments.length){var g=this[0],d=getComputedStyle(g,"");if(!g)return;if("string"==typeof b)return g.style[K(b)]||d.getPropertyValue(b);
if(I(b)){var s={};f.each(b,function(a,b){s[b]=g.style[K(b)]||d.getPropertyValue(b)});return s}}var h="";if("string"==a(b))!c&&0!==c?this.each(function(){this.style.removeProperty(l(b))}):h=l(b)+":"+("number"==typeof c&&!G[l(b)]?c+"px":c);else for(p in b)!b[p]&&0!==b[p]?this.each(function(){this.style.removeProperty(l(p))}):h+=l(p)+":"+("number"==typeof b[p]&&!G[l(p)]?b[p]+"px":b[p])+";";return this.each(function(){this.style.cssText+=";"+h})},index:function(a){return a?this.indexOf(f(a)[0]):this.parent().children().indexOf(this[0])},
hasClass:function(a){return!a?!1:A.some.call(this,function(a){return this.test(z(a))},x(a))},addClass:function(a){return!a?this:this.each(function(b){if("className"in this){E=[];var c=z(this);r(this,a,b,c).split(/\s+/g).forEach(function(a){f(this).hasClass(a)||E.push(a)},this);E.length&&z(this,c+(c?" ":"")+E.join(" "))}})},removeClass:function(a){return this.each(function(b){if("className"in this){if(a===t)return z(this,"");E=z(this);r(this,a,b,E).split(/\s+/g).forEach(function(a){E=E.replace(x(a),
" ")});z(this,E.trim())}})},toggleClass:function(a,b){return!a?this:this.each(function(c){var g=f(this);r(this,a,c,z(this)).split(/\s+/g).forEach(function(a){(b===t?!g.hasClass(a):b)?g.addClass(a):g.removeClass(a)})})},scrollTop:function(a){if(this.length){var b="scrollTop"in this[0];return a===t?b?this[0].scrollTop:this[0].pageYOffset:this.each(b?function(){this.scrollTop=a}:function(){this.scrollTo(this.scrollX,a)})}},scrollLeft:function(a){if(this.length){var b="scrollLeft"in this[0];return a===
t?b?this[0].scrollLeft:this[0].pageXOffset:this.each(b?function(){this.scrollLeft=a}:function(){this.scrollTo(a,this.scrollY)})}},position:function(){if(this.length){var a=this[0],b=this.offsetParent(),c=this.offset(),g=O.test(b[0].nodeName)?{top:0,left:0}:b.offset();c.top-=parseFloat(f(a).css("margin-top"))||0;c.left-=parseFloat(f(a).css("margin-left"))||0;g.top+=parseFloat(f(b[0]).css("border-top-width"))||0;g.left+=parseFloat(f(b[0]).css("border-left-width"))||0;return{top:c.top-g.top,left:c.left-
g.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||w.body;a&&!O.test(a.nodeName)&&"static"==f(a).css("position");)a=a.offsetParent;return a})}};f.fn.detach=f.fn.remove;["width","height"].forEach(function(a){var b=a.replace(/./,function(a){return a[0].toUpperCase()});f.fn[a]=function(c){var g,d=this[0];return c===t?e(d)?d["inner"+b]:n(d)?d.documentElement["scroll"+b]:(g=this.offset())&&g[a]:this.each(function(b){d=f(this);d.css(a,r(this,c,b,d[a]()))})}});["after",
"prepend","before","append"].forEach(function(b,c){var g=c%2;f.fn[b]=function(){var b,d=f.map(arguments,function(c){b=a(c);return"object"==b||"array"==b||null==c?c:y.fragment(c)}),s,h=1<this.length;return 1>d.length?this:this.each(function(a,b){s=g?b:b.parentNode;b=0==c?b.nextSibling:1==c?b.firstChild:2==c?b:null;var D=f.contains(w.documentElement,s);d.forEach(function(a){if(h)a=a.cloneNode(!0);else if(!s)return f(a).remove();s.insertBefore(a,b);D&&u(a,function(a){null!=a.nodeName&&"SCRIPT"===a.nodeName.toUpperCase()&&
((!a.type||"text/javascript"===a.type)&&!a.src)&&window.eval.call(window,a.innerHTML)})})})};f.fn[g?b+"To":"insert"+(c?"Before":"After")]=function(a){f(a)[b](this);return this}});y.Z.prototype=f.fn;y.uniq=L;y.deserializeValue=B;f.zepto=y;return f}();window.Zepto=Zepto;void 0===window.$&&(window.$=Zepto);
(function(a){"__proto__"in{}||a.extend(a.zepto,{Z:function(d,e){d=d||[];a.extend(d,a.fn);d.selector=e||"";d.__Z=!0;return d},isZ:function(d){return"array"===a.type(d)&&"__Z"in d}});try{getComputedStyle(void 0)}catch(d){var e=getComputedStyle;window.getComputedStyle=function(a){try{return e(a)}catch(d){return null}}}})(Zepto);
(function(a){function d(b){b=a(b);return!(!b.width()&&!b.height())&&"none"!==b.css("display")}function e(a,b){a=a.replace(/=#\]/g,'="#"]');var c,d,e=l.exec(a);e&&e[2]in k&&(c=k[e[2]],d=e[3],a=e[1],d&&(e=Number(d),d=isNaN(e)?d.replace(/^["']|["']$/g,""):e));return b(a,c,d)}var n=a.zepto,q=n.qsa,c=n.matches,k=a.expr[":"]={visible:function(){if(d(this))return this},hidden:function(){if(!d(this))return this},selected:function(){if(this.selected)return this},checked:function(){if(this.checked)return this},
parent:function(){return this.parentNode},first:function(a){if(0===a)return this},last:function(a,b){if(a===b.length-1)return this},eq:function(a,b,c){if(a===c)return this},contains:function(b,c,d){if(-1<a(this).text().indexOf(d))return this},has:function(a,b,c){if(n.qsa(this,c).length)return this}},l=/(.*):(\w+)(?:\(([^)]+)\))?$\s*/,x=/^\s*>/,b="Zepto"+ +new Date;n.qsa=function(c,d){return e(d,function(e,l,k){try{var u;!e&&l?e="*":x.test(e)&&(u=a(c).addClass(b),e="."+b+" "+e);var t=q(c,e)}catch(p){throw console.error("error performing selector: %o",
d),p;}finally{u&&u.removeClass(b)}return!l?t:n.uniq(a.map(t,function(a,b){return l.call(a,b,t,k)}))})};n.matches=function(a,b){return e(b,function(b,d,e){return(!b||c(a,b))&&(!d||d.call(a,null,e)===a)})}})(Zepto);
(function(a){a.fn.end=function(){return this.prevObject||a()};a.fn.andSelf=function(){return this.add(this.prevObject||a())};"filter add not eq first last find closest parents parent children siblings".split(" ").forEach(function(d){var e=a.fn[d];a.fn[d]=function(){var a=e.apply(this,arguments);a.prevObject=this;return a}})})(Zepto);
(function(a){function d(a){return a._zid||(a._zid=x++)}function e(a,b,c,s){b=n(b);if(b.ns)var e=RegExp("(?:^| )"+b.ns.replace(" "," .* ?")+"(?: |$)");return(z[d(a)]||[]).filter(function(a){return a&&(!b.e||a.e==b.e)&&(!b.ns||e.test(a.ns))&&(!c||d(a.fn)===d(c))&&(!s||a.sel==s)})}function n(a){a=(""+a).split(".");return{e:a[0],ns:a.slice(1).sort().join(" ")}}function q(c,e,g,s,f,h,l){var m=d(c),r=z[m]||(z[m]=[]);e.split(/\s/).forEach(function(d){if("ready"==d)return a(document).ready(g);var e=n(d);
e.fn=g;e.sel=f;e.e in p&&(g=function(b){var c=b.relatedTarget;if(!c||c!==this&&!a.contains(this,c))return e.fn.apply(this,arguments)});var w=(e.del=h)||g;e.proxy=function(a){a=k(a);if(!a.isImmediatePropagationStopped()){a.data=s;var g=w.apply(c,a._args==b?[a]:[a].concat(a._args));!1===g&&(a.preventDefault(),a.stopPropagation());return g}};e.i=r.length;r.push(e);"addEventListener"in c&&c.addEventListener(p[e.e]||u&&t[e.e]||e.e,e.proxy,e.del&&!u&&e.e in t||!!l)})}function c(a,b,c,s,f){var h=d(a);(b||
"").split(/\s/).forEach(function(b){e(a,b,c,s).forEach(function(b){delete z[h][b.i];"removeEventListener"in a&&a.removeEventListener(p[b.e]||u&&t[b.e]||b.e,b.proxy,b.del&&!u&&b.e in t||!!f)})})}function k(c,d){if(d||!c.isDefaultPrevented)if(d||(d=c),a.each(C,function(a,b){var e=d[a];c[a]=function(){this[b]=f;return e&&e.apply(d,arguments)};c[b]=E}),d.defaultPrevented!==b?d.defaultPrevented:"returnValue"in d?!1===d.returnValue:d.getPreventDefault&&d.getPreventDefault())c.isDefaultPrevented=f;return c}
function l(a){var c,d={originalEvent:a};for(c in a)!A.test(c)&&a[c]!==b&&(d[c]=a[c]);return k(d,a)}var x=1,b,h=Array.prototype.slice,m=a.isFunction,r=function(a){return"string"==typeof a},z={},B={},u="onfocusin"in window,t={focus:"focusin",blur:"focusout"},p={mouseenter:"mouseover",mouseleave:"mouseout"};B.click=B.mousedown=B.mouseup=B.mousemove="MouseEvents";a.event={add:q,remove:c};a.proxy=function(b,c){var g=2 in arguments&&h.call(arguments,2);if(m(b)){var s=function(){return b.apply(c,g?g.concat(h.call(arguments)):
arguments)};s._zid=d(b);return s}if(r(c))return g?(g.unshift(b[c],b),a.proxy.apply(null,g)):a.proxy(b[c],b);throw new TypeError("expected function");};a.fn.bind=function(a,b,c){return this.on(a,b,c)};a.fn.unbind=function(a,b){return this.off(a,b)};a.fn.one=function(a,b,c,d){return this.on(a,b,c,d,1)};var f=function(){return!0},E=function(){return!1},A=/^([A-Z]|returnValue$|layer[XY]$)/,C={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};
a.fn.delegate=function(a,b,c){return this.on(b,a,c)};a.fn.undelegate=function(a,b,c){return this.off(b,a,c)};a.fn.live=function(b,c){a(document.body).delegate(this.selector,b,c);return this};a.fn.die=function(b,c){a(document.body).undelegate(this.selector,b,c);return this};a.fn.on=function(d,e,g,s,f){var p,n,k=this;if(d&&!r(d))return a.each(d,function(a,b){k.on(a,e,g,b,f)}),k;!r(e)&&!m(s)&&!1!==s&&(s=g,g=e,e=b);if(m(g)||!1===g)s=g,g=b;!1===s&&(s=E);return k.each(function(b,m){f&&(p=function(a){c(m,
a.type,s);return s.apply(this,arguments)});e&&(n=function(b){var c,d=a(b.target).closest(e,m).get(0);if(d&&d!==m)return c=a.extend(l(b),{currentTarget:d,liveFired:m}),(p||s).apply(d,[c].concat(h.call(arguments,1)))});q(m,d,s,g,e,n||p)})};a.fn.off=function(d,e,g){var s=this;if(d&&!r(d))return a.each(d,function(a,b){s.off(a,e,b)}),s;!r(e)&&!m(g)&&!1!==g&&(g=e,e=b);!1===g&&(g=E);return s.each(function(){c(this,d,g,e)})};a.fn.trigger=function(b,c){b=r(b)||a.isPlainObject(b)?a.Event(b):k(b);b._args=c;
return this.each(function(){"dispatchEvent"in this?this.dispatchEvent(b):a(this).triggerHandler(b,c)})};a.fn.triggerHandler=function(b,c){var d,s;this.each(function(f,h){d=l(r(b)?a.Event(b):b);d._args=c;d.target=h;a.each(e(h,b.type||b),function(a,b){s=b.proxy(d);if(d.isImmediatePropagationStopped())return!1})});return s};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(b){a.fn[b]=
function(a){return a?this.bind(b,a):this.trigger(b)}});["focus","blur"].forEach(function(b){a.fn[b]=function(a){a?this.bind(b,a):this.each(function(){try{this[b]()}catch(a){}});return this}});a.Event=function(a,b){r(a)||(b=a,a=b.type);var c=document.createEvent(B[a]||"Events"),d=!0;if(b)for(var e in b)"bubbles"==e?d=!!b[e]:c[e]=b[e];c.initEvent(a,d,!0);return k(c)}})(Zepto);
(function(a){function d(b,d){var m=b[l],m=m&&q[m];if(void 0===d)return m||e(b);if(m){if(d in m)return m[d];var r=k(d);if(r in m)return m[r]}return c.call(a(b),d)}function e(b,c,d){var e=b[l]||(b[l]=++a.uuid);b=q[e]||(q[e]=n(b));void 0!==c&&(b[k(c)]=d);return b}function n(b){var c={};a.each(b.attributes||x,function(b,d){0==d.name.indexOf("data-")&&(c[k(d.name.replace("data-",""))]=a.zepto.deserializeValue(d.value))});return c}var q={},c=a.fn.data,k=a.camelCase,l=a.expando="Zepto"+ +new Date,x=[];a.fn.data=
function(b,c){return void 0===c?a.isPlainObject(b)?this.each(function(c,d){a.each(b,function(a,b){e(d,a,b)})}):0 in this?d(this[0],b):void 0:this.each(function(){e(this,b,c)})};a.fn.removeData=function(b){"string"==typeof b&&(b=b.split(/\s+/));return this.each(function(){var c=this[l],d=c&&q[c];d&&a.each(b||d,function(a){delete d[b?k(this):a]})})};["remove","empty"].forEach(function(b){var c=a.fn[b];a.fn[b]=function(){var a=this.find("*");"remove"===b&&(a=a.add(this));a.removeData();return c.call(this)}})})(Zepto);
(function(a){function d(b,c,d,e){if(b.global)return b=c||B,d=a.Event(d),a(b).trigger(d,e),!d.isDefaultPrevented()}function e(b){b.global&&0===a.active++&&d(b,null,"ajaxStart")}function n(a,b){var c=b.context;if(!1===b.beforeSend.call(c,a,b)||!1===d(b,c,"ajaxBeforeSend",[a,b]))return!1;d(b,c,"ajaxSend",[a,b])}function q(a,b,c,e){var f=c.context;c.success.call(f,a,"success",b);e&&e.resolveWith(f,[a,"success",b]);d(c,f,"ajaxSuccess",[b,c,a]);k("success",b,c)}function c(a,b,c,e,f){var h=e.context;e.error.call(h,
c,b,a);f&&f.rejectWith(h,[c,b,a]);d(e,h,"ajaxError",[c,e,a||b]);k(b,c,e)}function k(b,c,e){var f=e.context;e.complete.call(f,c,b);d(e,f,"ajaxComplete",[c,e]);e.global&&!--a.active&&d(e,null,"ajaxStop")}function l(){}function x(a){a&&(a=a.split(";",2)[0]);return a&&(a==C?"html":a==A?"json":f.test(a)?"script":E.test(a)&&"xml")||"text"}function b(a,b){return""==b?a:(a+"&"+b).replace(/[&?]{1,2}/,"?")}function h(c){c.processData&&c.data&&"string"!=a.type(c.data)&&(c.data=a.param(c.data,c.traditional));
if(c.data&&(!c.type||"GET"==c.type.toUpperCase()))c.url=b(c.url,c.data),c.data=void 0}function m(b,c,d,e){a.isFunction(c)&&(e=d,d=c,c=void 0);a.isFunction(d)||(e=d,d=void 0);return{url:b,data:c,success:d,dataType:e}}function r(b,c,d,e){var f,h=a.isArray(c),p=a.isPlainObject(c);a.each(c,function(c,s){f=a.type(s);e&&(c=d?e:e+"["+(p||"object"==f||"array"==f?c:"")+"]");!e&&h?b.add(s.name,s.value):"array"==f||!d&&"object"==f?r(b,s,d,c):b.add(c,s)})}var z=0,B=window.document,u,t,p=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
f=/^(?:text|application)\/javascript/i,E=/^(?:text|application)\/xml/i,A="application/json",C="text/html",D=/^\s*$/;a.active=0;a.ajaxJSONP=function(b,d){if(!("type"in b))return a.ajax(b);var e=b.jsonpCallback,f=(a.isFunction(e)?e():e)||"jsonp"+ ++z,h=B.createElement("script"),p=window[f],l,m=function(b){a(h).triggerHandler("error",b||"abort")},k={abort:m},r;d&&d.promise(k);a(h).on("load error",function(e,m){clearTimeout(r);a(h).off().remove();"error"==e.type||!l?c(null,m||"error",k,b,d):q(l[0],k,
b,d);window[f]=p;l&&a.isFunction(p)&&p(l[0]);p=l=void 0});if(!1===n(k,b))return m("abort"),k;window[f]=function(){l=arguments};h.src=b.url.replace(/\?(.+)=\?/,"?$1="+f);B.head.appendChild(h);0<b.timeout&&(r=setTimeout(function(){m("timeout")},b.timeout));return k};a.ajaxSettings={type:"GET",beforeSend:l,success:l,error:l,complete:l,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript, application/x-javascript",json:A,xml:"application/xml, text/xml",
html:C,text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};a.ajax=function(d){var f=a.extend({},d||{}),p=a.Deferred&&a.Deferred();for(u in a.ajaxSettings)void 0===f[u]&&(f[u]=a.ajaxSettings[u]);e(f);f.crossDomain||(f.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(f.url)&&RegExp.$2!=window.location.host);f.url||(f.url=window.location.toString());h(f);var m=f.dataType,k=/\?.+=\?/.test(f.url);k&&(m="jsonp");if(!1===f.cache||(!d||!0!==d.cache)&&("script"==m||"jsonp"==m))f.url=b(f.url,"_="+
Date.now());if("jsonp"==m)return k||(f.url=b(f.url,f.jsonp?f.jsonp+"=?":!1===f.jsonp?"":"callback=?")),a.ajaxJSONP(f,p);d=f.accepts[m];var r={},k=function(a,b){r[a.toLowerCase()]=[a,b]},A=/^([\w-]+:)\/\//.test(f.url)?RegExp.$1:window.location.protocol,v=f.xhr(),w=v.setRequestHeader,z;p&&p.promise(v);f.crossDomain||k("X-Requested-With","XMLHttpRequest");k("Accept",d||"*/*");if(d=f.mimeType||d)-1<d.indexOf(",")&&(d=d.split(",",2)[0]),v.overrideMimeType&&v.overrideMimeType(d);if(f.contentType||!1!==
f.contentType&&f.data&&"GET"!=f.type.toUpperCase())k("Content-Type",f.contentType||"application/x-www-form-urlencoded");if(f.headers)for(t in f.headers)k(t,f.headers[t]);v.setRequestHeader=k;v.onreadystatechange=function(){if(4==v.readyState){v.onreadystatechange=l;clearTimeout(z);var b,d=!1;if(200<=v.status&&300>v.status||304==v.status||0==v.status&&"file:"==A){m=m||x(f.mimeType||v.getResponseHeader("content-type"));b=v.responseText;try{"script"==m?(0,eval)(b):"xml"==m?b=v.responseXML:"json"==m&&
(b=D.test(b)?null:a.parseJSON(b))}catch(e){d=e}d?c(d,"parsererror",v,f,p):q(b,v,f,p)}else c(v.statusText||null,v.status?"error":"abort",v,f,p)}};if(!1===n(v,f))return v.abort(),c(null,"abort",v,f,p),v;if(f.xhrFields)for(t in f.xhrFields)v[t]=f.xhrFields[t];v.open(f.type,f.url,"async"in f?f.async:!0,f.username,f.password);for(t in r)w.apply(v,r[t]);0<f.timeout&&(z=setTimeout(function(){v.onreadystatechange=l;v.abort();c(null,"timeout",v,f,p)},f.timeout));v.send(f.data?f.data:null);return v};a.get=
function(){return a.ajax(m.apply(null,arguments))};a.post=function(){var b=m.apply(null,arguments);b.type="POST";return a.ajax(b)};a.getJSON=function(){var b=m.apply(null,arguments);b.dataType="json";return a.ajax(b)};a.fn.load=function(b,c,d){if(!this.length)return this;var e=this,f=b.split(/\s/),h;b=m(b,c,d);var l=b.success;1<f.length&&(b.url=f[0],h=f[1]);b.success=function(b){e.html(h?a("<div>").html(b.replace(p,"")).find(h):b);l&&l.apply(e,arguments)};a.ajax(b);return this};var w=encodeURIComponent;
a.param=function(a,b){var c=[];c.add=function(a,b){this.push(w(a)+"="+w(b))};r(c,a,b);return c.join("&").replace(/%20/g,"+")}})(Zepto);
(function(a){a.fn.serializeArray=function(){var d,e,n=[];a([].slice.call(this.get(0).elements)).each(function(){d=a(this);e=d.attr("type");this.name&&"fieldset"!=this.nodeName.toLowerCase()&&(!this.disabled&&"submit"!=e&&"reset"!=e&&"button"!=e&&("radio"!=e&&"checkbox"!=e||this.checked))&&n.push({name:d.attr("name"),value:d.val()})});return n};a.fn.serialize=function(){var a=[];this.serializeArray().forEach(function(e){a.push(encodeURIComponent(e.name)+"="+encodeURIComponent(e.value))});return a.join("&")};
a.fn.submit=function(d){d?this.bind("submit",d):this.length&&(d=a.Event("submit"),this.eq(0).trigger(d),d.isDefaultPrevented()||this.get(0).submit());return this}})(Zepto);
(function(a,d){var e="",n,q=window.document.createElement("div"),c=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i,k,l,x,b,h,m,r,z,B,u={};a.each({Webkit:"webkit",Moz:"",O:"o"},function(a,b){if(q.style[a+"TransitionProperty"]!==d)return e="-"+a.toLowerCase()+"-",n=b,!1});k=e+"transform";u[l=e+"transition-property"]=u[x=e+"transition-duration"]=u[h=e+"transition-delay"]=u[b=e+"transition-timing-function"]=u[m=e+"animation-name"]=u[r=e+"animation-duration"]=u[B=e+"animation-delay"]=
u[z=e+"animation-timing-function"]="";a.fx={off:n===d&&q.style.transitionProperty===d,speeds:{_default:400,fast:200,slow:600},cssPrefix:e,transitionEnd:n?n+"TransitionEnd":"transitionend",animationEnd:n?n+"AnimationEnd":"animationend"};a.fn.animate=function(b,c,e,h,l){a.isFunction(c)&&(h=c,c=e=d);a.isFunction(e)&&(h=e,e=d);a.isPlainObject(c)&&(e=c.easing,h=c.complete,l=c.delay,c=c.duration);c&&(c=("number"==typeof c?c:a.fx.speeds[c]||a.fx.speeds._default)/1E3);l&&(l=parseFloat(l)/1E3);return this.anim(b,
c,e,h,l)};a.fn.anim=function(e,p,f,n,q){var C,D={},w,g="",s=this,G,H=a.fx.transitionEnd,J=!1;p===d&&(p=a.fx.speeds._default/1E3);q===d&&(q=0);a.fx.off&&(p=0);if("string"==typeof e)D[m]=e,D[r]=p+"s",D[B]=q+"s",D[z]=f||"linear",H=a.fx.animationEnd;else{w=[];for(C in e)c.test(C)?g+=C+"("+e[C]+") ":(D[C]=e[C],w.push(C.replace(/([a-z])([A-Z])/,"$1-$2").toLowerCase()));g&&(D[k]=g,w.push(k));0<p&&"object"===typeof e&&(D[l]=w.join(", "),D[x]=p+"s",D[h]=q+"s",D[b]=f||"linear")}G=function(b){if("undefined"!==
typeof b){if(b.target!==b.currentTarget)return;a(b.target).unbind(H,G)}else a(this).unbind(H,G);J=!0;a(this).css(u);n&&n.call(this)};0<p&&(this.bind(H,G),setTimeout(function(){J||G.call(s)},1E3*p+25));this.size()&&this.get(0).clientLeft;this.css(D);0>=p&&setTimeout(function(){s.each(function(){G.call(this)})},0);return this};q=null})(Zepto);
(function(a,d){function e(c,e,b,h,m){"function"==typeof e&&!m&&(m=e,e=d);b={opacity:b};h&&(b.scale=h,c.css(a.fx.cssPrefix+"transform-origin","0 0"));return c.animate(b,e,null,m)}function n(d,k,b,h){return e(d,k,0,b,function(){c.call(a(this));h&&h.call(this)})}var q=a.fn.show,c=a.fn.hide,k=a.fn.toggle;a.fn.show=function(a,c){q.call(this);a===d?a=0:this.css("opacity",0);return e(this,a,1,"1,1",c)};a.fn.hide=function(a,e){return a===d?c.call(this):n(this,a,"0,0",e)};a.fn.toggle=function(c,e){return c===
d||"boolean"==typeof c?k.call(this,c):this.each(function(){var b=a(this);b["none"==b.css("display")?"show":"hide"](c,e)})};a.fn.fadeTo=function(a,c,b){return e(this,a,c,null,b)};a.fn.fadeIn=function(a,c){var b=this.css("opacity");0<b?this.css("opacity",0):b=1;return q.call(this).fadeTo(a,b,c)};a.fn.fadeOut=function(a,c){return n(this,a,null,c)};a.fn.fadeToggle=function(c,d){return this.each(function(){var b=a(this);b[0==b.css("opacity")||"none"==b.css("display")?"fadeIn":"fadeOut"](c,d)})}})(Zepto);
(function(a){function d(){b=null;c.last&&(c.el.trigger("longTap"),c={})}function e(){k&&clearTimeout(k);l&&clearTimeout(l);x&&clearTimeout(x);b&&clearTimeout(b);k=l=x=b=null;c={}}function n(a){return("touch"==a.pointerType||a.pointerType==a.MSPOINTER_TYPE_TOUCH)&&a.isPrimary}function q(a,b){return a.type=="pointer"+b||a.type.toLowerCase()=="mspointer"+b}var c={},k,l,x,b,h;a(document).ready(function(){var m,r,z=0,B=0,u,t;"MSGesture"in window&&(h=new MSGesture,h.target=document.body);a(document).bind("MSGestureEnd",
function(a){if(a=1<a.velocityX?"Right":-1>a.velocityX?"Left":1<a.velocityY?"Down":-1>a.velocityY?"Up":null)c.el.trigger("swipe"),c.el.trigger("swipe"+a)}).on("touchstart MSPointerDown pointerdown",function(e){if(!(t=q(e,"down"))||n(e))u=t?e:e.touches[0],e.touches&&1===e.touches.length&&c.x2&&(c.x2=void 0,c.y2=void 0),m=Date.now(),r=m-(c.last||m),c.el=a("tagName"in u.target?u.target:u.target.parentNode),k&&clearTimeout(k),c.x1=u.pageX,c.y1=u.pageY,0<r&&250>=r&&(c.isDoubleTap=!0),c.last=m,b=setTimeout(d,
750),h&&t&&h.addPointer(e.pointerId)}).on("touchmove MSPointerMove pointermove",function(a){if(!(t=q(a,"move"))||n(a))u=t?a:a.touches[0],b&&clearTimeout(b),b=null,c.x2=u.pageX,c.y2=u.pageY,z+=Math.abs(c.x1-c.x2),B+=Math.abs(c.y1-c.y2)}).on("touchend MSPointerUp pointerup",function(d){if(!(t=q(d,"up"))||n(d))b&&clearTimeout(b),b=null,c.x2&&30<Math.abs(c.x1-c.x2)||c.y2&&30<Math.abs(c.y1-c.y2)?x=setTimeout(function(){c.el.trigger("swipe");c.el.trigger("swipe"+(Math.abs(c.x1-c.x2)>=Math.abs(c.y1-c.y2)?
0<c.x1-c.x2?"Left":"Right":0<c.y1-c.y2?"Up":"Down"));c={}},0):"last"in c&&(30>z&&30>B?l=setTimeout(function(){var b=a.Event("tap");b.cancelTouch=e;c.el.trigger(b);c.isDoubleTap?(c.el&&c.el.trigger("doubleTap"),c={}):k=setTimeout(function(){k=null;c.el&&c.el.trigger("singleTap");c={}},250)},0):c={}),z=B=0}).on("touchcancel MSPointerCancel pointercancel",e);a(window).on("scroll",e)});"swipe swipeLeft swipeRight swipeUp swipeDown doubleTap tap singleTap longTap".split(" ").forEach(function(b){a.fn[b]=
function(a){return this.on(b,a)}})})(Zepto);(function(a,d){var e=window.KingSoft=window.K||{},n=document.createElement("div").style,q={};window.K=e;e.supports=e.supports||q;var c=e.camelCase=function(a){return a.replace(/^-ms-/,"ms-").replace(/-([a-z]|[0-9])/ig,function(a,b){return(b+"").toUpperCase()})};e.uncamelCase=function(a){return a.replace(/([A-Z]|^ms)/g,"-$1").toLowerCase()};var k=e.cssVendor=function(){var a=["-webkit-","-moz-",""],d=0;do if(c(a[d]+"transform")in n)return a[d];while(++d<a.length);return""}();e.transitionend={"-webkit-":"webkitTransitionEnd",
"-moz-":"transitionend","":"transitionend"}[k];var l=e.isCSS=function(a){var d=c(a);a=c(k+a);return d in n&&d||a in n&&a||""};e.isArrayLike=function(a){var c=e.type(a);return!!a&&"function"!=c&&"string"!=c&&(0===a.length||a.length&&a.length-1 in a)};var x=e.type=function(){for(var a="Boolean Number String Function Array Date RegExp Object Error Undefined Null".split(" "),c=0,d={};c<a.length;)e["is"+a[c]]=function(){var d=a[c].toLowerCase();return function(a){return x(a)===d}}(),d["[object "+a[c]+
"]"]=a[c++].toLowerCase();return function(a){return null==a?String(a):"object"==typeof a?d[d.toString.call(a)]||"object":typeof a}}();e.getQueryValue=function(a){return(a=decodeURIComponent(location.search).match(RegExp(a+"=([^&]*)")))&&a[1]||""};e.getAbsUrl=function(a){var c=document.createElement("a");c.href=a;return/^http/i.test(c.href)?c.href:c.getAttribute("href",4)};a.each("transform transition animation perspective border-image border-radius box-shadow background-size background-clip text-shadow min-height opacity".split(" "),
function(a,d){q[c(d)]=!!l(d)});q.touch="createTouch"in document||"ontouchstart"in window;q.canvas="function"==typeof document.createElement("canvas").getContext;q.svg=!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect;e.transform=l("transform");e.transition=l("transition");e.animation=l("animation");e.EVENTS="PointerEvent"in window?"pointerdown pointermove pointerup pointercancel":q.touch?"touchstart touchmove touchend touchcancel":"mousedown mousemove mouseup";
q.touch||a(document).click(function(b){var c=a.Event("tap");a(b.target||b.srcElement).trigger(c)});e.Panel=createClass(function(){this.zIndex=this.constructor.prototype.zIndex++;this.mask=a('<div class="Mask" style="z-index:'+this.zIndex+';"></div>');this.frame=a('<div class="Panel" style="z-index:'+this.zIndex+';"></div>')},{zIndex:100,setContent:function(a){this.frame.html(a);return this},show:function(b){a.contains(document.body,this.frame[0])||(this.mask.appendTo("body"),this.frame.appendTo("body"));
this.frame.fadeIn(400,b);this.mask.fadeIn(400);return this},hide:function(a){this.frame.fadeOut(400,a);this.mask.fadeOut(400);return this},destroy:function(a){this.hide(function(){this.frame.remove();this.mask.remove();a&&a()}.bind(this))}});e.alert=function(a){var c=e.Panel().setContent('<a class="close"></a><div class="text">'+a+"</div>");c.frame.addClass("syswin").find(".close").tap(function(){c.destroy()});c.show()}})(Zepto);
