/*!
 * Author: liujiaqi@cmcm.com
 * Date: 2015-06-23 11:53:16
 *
 * include "createClass.js"
 * include "storage.js"
 * include "lazyload.js"
 * include "sketch.js"
 * include "share.js"
 * include "zepto.min.js"
 * include "common.js"
 */
!function(a,k,g){function t(a,d){for(var h=0,e=a.length,f=[],q;h<e;h++)"undefined"!==typeof(q=d(a[h],h,a))&&f.push(q);return f}function r(a,d,h,e,f){return function(){var q=this._super,v=0,u;if(h[f]){a:{u=arguments.callee.caller;var s;if(u)for(s in e)if(e[s]===u){u=!0;break a}u=!1}if(u)a=h[f];else if(!p(a=e[f]||!e["private:"+f]&&this[f]))throw Error("Cant not run a private method!");}for(this._super=new Function;u=d[v++];){if(null==f){this._super=u.prototype._self||u;break}if(p(u.prototype[f])){this._super=
u.prototype[f];break}}v=a.apply(this,arguments);this._super=q;return v}}function m(){for(var a=arguments.length,d=arguments[0],h=1,e,f,q;h<a;h++)if(null!=(e=arguments[h]))for(f in e)if(d!==(q=e[f]))d[f]=q;return d}function w(a,d){var h=p(a),e=p(d);return h==e?0:h?-1:1}function p(a){return"function"==typeof a}var x=a[k]=function(){function a(f){q.apply(this,f)}function d(){return new a(arguments)}if(this instanceof x)throw new TypeError(k+" is not a constructor");var h,e,f=t(arguments,function(a){if(p(a)){var f;
a:{for(f in a.prototype){f=!0;break a}f=void 0}if(f)e||(e=a.prototype._self||a);else{h=a;return}}return a}),q=h||e||new Function,v=[],u={},s={_self_:q},l={_self:q=r(q,v,u,s),extend:function(){return m.apply(null,(this===l?[]:[this]).concat(t([{constructor:d}].concat(t(arguments,function(a){var f,e,c,q,n,B=[];if(p(a))v.push(c=a);else if(a&&"object"==typeof a){c=a;q={};for(f in c)if(c.hasOwnProperty(f)&&p(n=c[f])&&"constructor"!=f){e=f.split(":");if(1<e.length)switch(a=e.shift(),e=e.join(":"),a){case "private":B.push(f);
u[e]=n;break;case "static":B.push(f);d[e]=n;continue;default:e=f}else e=f;q[e]=r(s[f]=n,v,u,s,e)}for(;f=B.shift();)delete c[f]}return m(c,q)}),l).sort(w),function(a){var f;p(a)&&(f=new Function,f.prototype=a.prototype,a=new f);return a||f})))},isInstanceof:function(a){var f;if(!(f=this instanceof a))a:{for(var e=0,c=v.length;e<c;e++)if(f=v[e].prototype.isInstanceof,v[e]===a||f&&f.call(this,a)){f=!0;break a}f=!1}return f}};a.prototype=d.fn=d.prototype=l.extend.apply(l,f);d.extend=function(){return x.apply(null,
[].slice.call(arguments,0).concat(this))};return d}}(window,"createClass");(function(a,k,g,t){var r=a.document,m=a.localStorage||a.globalStorage&&a.globalStorage[location.hostname];k.prototype=k;var w=function(a,c){return(m?{length:0,init:function(){this.name=a?a+"/":"";this.getStorages();return this},getStorages:function(){for(var a=this.storages={},c=this.keys=[],e=0,f=m.length,q,v,u=RegExp("^"+this.name.replace(/([\.\?\+\*\[\]\(\)\^\$\/\|\\])/g,"\\$1"),"i");e<f;e++)q=m.key(e),u.test(q)&&(v=q.replace(u,""),c.push(v),a[v]=m.getItem(q));this.length=c.length;return this},
key:function(a){return this.keys[a]},getItem:function(a){return this.storages[a]},setItem:function(a,c){m.setItem(this.name+a,c);return this.getStorages()},removeItem:function(a){m.removeItem(this.name+a);return this.getStorages()},clear:function(){if(this.name)for(var a=this.length,c=0;c++<a;)this.removeItem(this.key(0));else m.clear();return this.getStorages()}}:{length:0,userData:c||r.getElementsByTagName("head")[0],init:function(){this.name=a?"_"+a:"";try{this.userData.addBehavior("#default#userdata"),
this.refresh()}catch(c){}return this},load:function(){try{this.userData.load("oXMLBranch"+this.name),this.storeNode=this.userData.xmlDocument.firstChild}catch(a){}},refresh:function(){this.load();this.length=this.storeNode.attributes.length;return this},key:function(a){this.load();return this.storeNode.attributes[a].nodeName.replace(/^_/,"")},getItem:function(a){this.load();return this.userData.getAttribute("_"+a)},setItem:function(a,c){this.load();this.userData.setAttribute("_"+a,c);return this.save()},
removeItem:function(a){this.load();this.userData.removeAttribute("_"+a);return this.save()},clear:function(){this.load();this.userData.xmlDocument.removeChild(this.storeNode);return this.save()},save:function(){this.userData.save("oXMLBranch"+this.name);return this.refresh()}}).init()},p;t={version:"2.4",constructor:k,init:function(a,c){"string"!=typeof a&&(c=a,a="");this.storage=w(a,c);return this.test()},test:function(){try{this.support=this.set("__storage__",1)&&this.remove("__storage__")}catch(a){this.support=
!1}return this},refresh:function(){this.storages=this.getStorages();return this},has:function(a){return null!=this.get(a)},get:function(a){return this.storages[a]},set:function(a,c){this.storage.setItem(a,c);return this.refresh().has(a)},remove:function(a){this.storage.removeItem(a);return!this.refresh().has(a)},clear:function(){this.storage.clear();return!this.refresh().size()},size:function(){return this.storage.length},getStorages:function(){for(var a={},c=this.storage,d=0,h=c&&c.length||0,e;d<
h;d++)e=c.key(d),a[e]=c.getItem(e);return a},key:function(a){return this.storage.key(a)}};for(p in t)k[p]=t[p];return a[g]=k.init()})(window,function(a,k){if(!(this instanceof arguments.callee))return new arguments.callee(a,k);this.init(a,k)},"storage");(function(a,k,g,t){var r=a.document,m=function(a){var e=0,d=0;if("getBoundingClientRect"in a)a=a.getBoundingClientRect(),e=a.top+x,d=a.left+c;else{e+=a.scrollTop||0;for(d+=a.scrollLeft||0;a;)d+=a.offsetLeft||0,e+=a.offsetTop||0,a=a.offsetParent}return{top:e,left:d}},w=function(f,e,d){return null==e?f.lazyData||(f.lazyData={ret:[],bind:null,timer:null,lastTime:0,tick:function(){var e=0,d=w(f),q=d.ret,h=r.documentElement,v=r.body,g=null!=f&&f==f.window;d.WST=(g?f.pageYOffset||h&&h.scrollTop||v.scrollTop:
m(f).top)||0;d.WSL=(g?f.pageXOffset||h&&h.scrollLeft||v.scrollLeft:m(f).left)||0;d.WH=(g?f.innerHeight||h&&h.clientHeight||v.clientHeight:f.clientHeight)||0;d.WW=(g?f.innerWidth||h&&h.clientWidth||v.clientWidth:f.clientWidth)||0;g&&(x=d.WST,c=d.WSL);for(;e<q.length;)q[e].check().length?e++:delete d.ret.splice(e,1)[0].checking;if(!d.ret.length){a:{try{var A=w(f,"resize");a.removeEventListener?(a.removeEventListener("resize",A,!1),f.removeEventListener("scroll",A,!1)):(a.detachEvent("onresize",A),f.detachEvent("onscroll",
A))}catch(y){e=!1;break a}e=!0}d.bind=!e}},resize:function(){var a=w(f),e=+new Date;clearTimeout(a.timer);100<e-a.lastTime?(a.lastTime=e,a.tick()):a.timer=setTimeout(a.resize,100-e+a.lastTime)}}):null==d?w(f)[e]:w(f)[e]=d},p=function(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?d[h.call(a)]||"object":typeof a},x=0,c=0;t="Boolean Number String Function Array Date RegExp Object Error".split(" ");for(var d={},h=d.toString,e=0;e<t.length;)d["[object "+t[e]+"]"]=t[e++].toLowerCase();
g.fn=g.prototype={constructor:g,length:0,splice:[].splice,dcb:function(){var a=this.getAttribute("data-original");a&&(this.src=a)},init:function(f,e,c){var d,h=p(e);if("function"==h)c=e;else if("object"==h&&(c=e.callback,d=e.container,e=e.range,this.isArrayLike(d)&&(d=d[0]),"string"==p(d)&&(d=r.getElementById(d)),null==d||1!=d.nodeType||"body"==d.nodeName.toLowerCase()||"html"==d.nodeName.toLowerCase()))d=a;this.cb=c||this.dcb;this.range=parseFloat(e)||0;this.container=d||a;return this.push(f)},push:function(e){"string"==
p(e)&&(e=r.getElementById(e));this.merge(e);if(this.length&&(e=w(this.container),this.checking||(e.ret.push(this),this.checking=!0),e.resize(),!e.bind)){var c;a:{var d=this.container;try{c=w(d,"resize"),a.addEventListener?(a.addEventListener("resize",c,!1),d.addEventListener("scroll",c,!1)):(a.attachEvent("onresize",c),d.attachEvent("onscroll",c))}catch(h){c=!1;break a}c=!0}e.bind=c}return this},isArrayLike:function(a){var e=p(a);return!!a&&"function"!=e&&"string"!=e&&(0===a.length||a.length&&a.length-
1 in a)},merge:function(a){var e=this.length,c=0;for(a=this.isArrayLike(a)?a:[a];c<a.length;)a[c]&&1==a[c].nodeType&&(this[e++]=a[c]),c++;this.length=e;return this},check:function(){for(var a=0,e=this.range,c=w(this.container),d,h;a<this.length;){d=this[a];h=m(d);var l=d,g=r.documentElement;!("none"==(l.currentStyle||getComputedStyle(l,null)||l.style).display||g!==l&&!(g.contains?g.contains(l):g.compareDocumentPosition&&g.compareDocumentPosition(b)&16))&&h.top+d.offsetHeight+e>=c.WST&&h.top-e<=c.WST+
c.WH&&h.left+d.offsetWidth+e>=c.WSL&&h.left-e<=c.WSL+c.WW?this.cb.call(this.splice(a,1)[0]):a++}return this},empty:function(){this.length=0;return this}};g.fn.init.prototype=g.fn;return a[k]=g})(window,"LazyLoad",function(a,k,g){return new arguments.callee.fn.init(a,k,g)});(function(a,k,g){function t(a){return(a+"").replace(/-([a-z]|[0-9])/ig,function(a,e){return(e+"").toUpperCase()})}function r(a){var f={},h,g;f.oldEvent=a;f.type=a.type.toLowerCase();f.eventType=x[f.type]||f.type;f.eventCode=c[f.type]||0;f.preventDefault=function(){a.preventDefault()};h=d[f.eventType];switch(f.eventType){case "mouse":case "pointer":g=a.pointerId||0;3==f.eventCode?delete h[g]:h[g]=a;f.changedPointers=[{id:g,clientX:a.clientX,clientY:a.clientY}];f.pointers=Object.keys(h).map(function(a){return{id:a,
clientX:h[a].clientX,clientY:h[a].clientY}});break;case "touch":d[f.eventType]=h={},f.changedPointers=p.call(a.changedTouches).map(function(a){return{id:a.identifier,clientX:a.clientX,clientY:a.clientY}}),f.pointers=p.call(d[f.eventType]=h=a.touches).map(function(a){return{id:a.identifier,clientX:a.clientX,clientY:a.clientY}})}if(g=f.pointers[0])f.clientX=g.clientX,f.clientY=g.clientY;f.length=f.pointers.length;return f}var m={start:1,down:1,move:2,end:3,up:3,cancel:3},w=[],p=[].slice,x={},c={},d=
{},h=a.devicePixelRatio||1;"function"==typeof[].forEach&&["mouse","touch","pointer","MSPointer-"].forEach(function(a){var f=/pointer/i.test(a)?"pointer":a;Object.keys(m).forEach(function(h){var g=m[h];h=t(a+h);w.push(h);d[f]={};x[h.toLowerCase()]=f;c[h.toLowerCase()]=g})});k.prototype={constructor:k,lineWidth:5,color:"#000",erase:!1,bgcolor:"transparent",init:function(a){this.events={};this.actions=[];this.ctx=this.canvas.getContext("2d");"object"==typeof a&&"width height lineWidth color bgcolor multi".split(" ").forEach(function(c){this[c]=
"undefined"==typeof a[c]?this[c]:a[c]}.bind(this));w.forEach(function(a){this.canvas.addEventListener(a,this,!1)}.bind(this));var c=[];this.on({start:function(){this.moving||(c=[]);c[arguments[2]]={width:this.lineWidth,color:this.color,erase:this.erase,pens:[arguments]}},move:function(){var a=c[arguments[2]];a.pens.push(arguments);this.draw({width:a.width,color:a.color,erase:a.erase,pens:a.pens.slice(-2)})},end:function(a){c[a]&&1<c[a].pens.length&&this.actions.push(c[a])},redraw:function(){var a=
this.ctx;"transparent"!=this.bgcolor&&(a.fillStyle=this.bgcolor,a.fillRect(0,0,this.width,this.height))}}).clear()},handleEvent:function(a){a=r(a);var c=this.canvas.getBoundingClientRect(),d=!this.pointerType||this.pointerType==a.eventType;switch(a.eventCode){case 1:this.pointerType||(this.pointerType=a.eventType);d&&(this.multi||2>a.length?a.changedPointers.forEach(function(a){this.fire("start",a.clientX-c.left,a.clientY-c.top,a.id);this.moving=!0}.bind(this)):a.pointers.forEach(function(a){this.fire("end",
a.id)}.bind(this)));break;case 2:if(this.moving&&d&&(this.multi||2>a.length))a.preventDefault(),a.changedPointers.forEach(function(a){this.fire("move",a.clientX-c.left,a.clientY-c.top,a.id)}.bind(this));break;case 3:this.moving&&d&&(this.multi||!a.length?a.changedPointers.forEach(function(a){this.fire("end",a.id)}.bind(this)):a.pointers.forEach(function(a){this.fire("start",a.clientX-c.left,a.clientY-c.top,a.id)}.bind(this)),a.length||(delete this.moving,delete this.pointerType))}},on:function(a,
c){"object"==typeof a?Object.keys(a).forEach(function(c){this.on(c,a[c])}.bind(this)):(this.events[a]||(this.events[a]=[]),this.events[a].push(c));return this},fire:function(a){var c=[].slice.call(arguments,1);(this.events[a]||[]).forEach(function(a){"function"==typeof a&&a.apply(this,c)}.bind(this));return this},draw:function(a){var c=this.ctx,d=!this.bgcolor||"transparent"==this.bgcolor;c.lineWidth=a.width;c.lineJoin=c.lineCap="round";c.strokeStyle=a.erase?d?"#000":this.bgcolor:a.color;c.globalCompositeOperation=
a.erase&&d?"destination-out":"source-over";c.beginPath();a.pens.forEach(function(a,d){c[d?"lineTo":"moveTo"].apply(c,a)});c.stroke();return this},reDraw:function(){this.ctx.clearRect(0,0,this.width,this.height);this.fire("redraw");this.actions.forEach(this.draw.bind(this));return this},cancel:function(a){this.actions.splice(-(a||1));return this.reDraw()},clear:function(){this.actions.length=0;return this.reDraw()},toDataUrl:function(a){return this.canvas.toDataURL(a)},toBlob:function(){return(this.canvas.toBlob||
function(c,d){if("mozGetAsFile"in this)return c(this.mozGetAsFile("blob",d));var h=this.toDataURL(d).split(","),g=a.atob(h[1]),m=new Uint8Array(g.length),s,l;s=0;for(l=m.length;s<l;s++)m[s]=g.charCodeAt(s);c(new Blob([m.buffer],{type:d||h[0].split(/[:;]/)[1]}))}).apply(this.canvas,arguments)}};"function"==typeof Object.defineProperties&&(["width","height"].forEach(function(a){Object.defineProperty(k.prototype,a,{get:function(){return this.canvas[a]/h},set:function(c){this.canvas[a]=c*h;this.ctx.scale(h,
h)},enumerable:!0})}),Object.defineProperty(k.prototype,"steps",{get:function(){return this.actions.length},enumerable:!0}));a.Sketch=k})(window,function(a,k){if(!(this instanceof arguments.callee))return new arguments.callee(a,k);this.canvas="string"==typeof a?document.getElementById(a):a;this.init(k)});(function(a,k){a.Share={type:"pc",data:{title:document.title,img:"",desc:document.title,url:location.href,success:function(){},fail:function(){},complete:function(){}},init:function(){var a=this,k=["menu:share:appmessage","menu:share:timeline","menu:share:qq","menu:share:weiboApp"];"addEventListener"in document&&document.addEventListener("WeixinJSBridgeReady",function(){a.type="weixin";var r=new XMLHttpRequest;r.open("GET","http://cn.cmcm.com/wxjs/?type=cmcm&url="+encodeURIComponent(location.href.replace(/#.*$/,
"")),!0);r.onreadystatechange=function(){if(4==r.readyState&&200==r.status){var a=JSON.parse(r.responseText),g={verifyJsApiList:k};g.appId=a.appId;g.verifyAppId=a.appId;g.verifySignType="sha1";g.verifyTimestamp=a.timestamp+"";g.verifyNonceStr=a.nonceStr;g.verifySignature=a.signature;WeixinJSBridge.invoke("preVerifyJSAPI",g,function(a){})}};r.send();k.forEach(function(m){WeixinJSBridge.on(m,function(k){var p=a.data;k={img_url:p.img,desc:p.desc,title:p.title,link:p.url};var t;switch(m.split(":")[2]){case "appmessage":t=
"sendAppMessage";break;case "timeline":k.title=p.desc;k.desc=p.title;t="shareTimeline";break;case "qq":t="shareQQ";break;case "weiboApp":t="shareWeiboApp"}WeixinJSBridge.invoke(t,k,function(a){/\:(confirm|ok)$/i.test(a.err_msg)?p.success&&p.success(a):p.fail&&p.fail(a);p.complete&&p.complete(a)})})})},!1);if("undefined"!=typeof android||"undefined"!=typeof cm_web_app)this.type="cm",this.cmObj=window.android||window.cm_web_app;return this},update:function(a){var k=this.data,r;for(r in a)k[r]=a[r];
switch(this.type){case "cm":try{this.cmObj.updatesharedata(k.title,k.img,k.desc,k.url)}catch(m){}}},share:function(a){var k=this.data;"undefined"!=typeof a&&this.update(a);switch(this.type){case "cm":try{"function"==typeof this.cmObj.share?this.cmObj.share(1,k.url,k.title,k.desc,k.img):this.cmObj.sharescore()}catch(r){}}}}})(window);var Zepto=function(){function a(a){return null==a?String(a):M[S.call(a)]||"object"}function k(H){return"function"==a(H)}function g(a){return null!=a&&a==a.window}function t(a){return null!=a&&a.nodeType==a.DOCUMENT_NODE}function r(H){return"object"==a(H)}function m(a){return r(a)&&!g(a)&&Object.getPrototypeOf(a)==Object.prototype}function w(a){return A.call(a,function(a){return null!=a})}function p(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,
"$1_$2").replace(/_/g,"-").toLowerCase()}function x(a){return a in B?B[a]:B[a]=RegExp("(^|\\s)"+a+"(\\s|$)")}function c(a){return"children"in a?C.call(a.children):l.map(a.childNodes,function(a){if(1==a.nodeType)return a})}function d(a,c,e){for(s in c)e&&(m(c[s])||I(c[s]))?(m(c[s])&&!m(a[s])&&(a[s]={}),I(c[s])&&!I(a[s])&&(a[s]=[]),d(a[s],c[s],e)):c[s]!==u&&(a[s]=c[s])}function h(a,c){return null==c?l(a):l(a).filter(c)}function e(a,c,d,e){return k(c)?c.call(a,d,e):c}function f(a,c){var d=a.className||
"",e=d&&d.baseVal!==u;if(c===u)return e?d.baseVal:d;e?d.baseVal=c:a.className=c}function q(a){var c;try{return a?"true"==a||("false"==a?!1:"null"==a?null:!/^0/.test(a)&&!isNaN(c=Number(a))?c:/^[\[\{]/.test(a)?l.parseJSON(a):a):a}catch(d){return a}}function v(a,c){c(a);for(var d=0,e=a.childNodes.length;d<e;d++)v(a.childNodes[d],c)}var u,s,l,E,D=[],C=D.slice,A=D.filter,y=window.document,n={},B={},F={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},G=/^\s*<(\w+|!)[^>]*>/,
J=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,T=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,O=/^(?:body|html)$/i,U=/([A-Z])/g,V="val css html text data width height offset".split(" "),N=y.createElement("table"),P=y.createElement("tr"),Q={tr:y.createElement("tbody"),tbody:N,thead:N,tfoot:N,td:P,th:P,"*":y.createElement("div")},W=/complete|loaded|interactive/,X=/^[\w-]*$/,M={},S=M.toString,z={},K,L,R=y.createElement("div"),Y={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",
maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},I=Array.isArray||function(a){return a instanceof Array};z.matches=function(a,c){if(!c||!a||1!==a.nodeType)return!1;var d=a.webkitMatchesSelector||a.mozMatchesSelector||a.oMatchesSelector||a.matchesSelector;if(d)return d.call(a,c);var e;e=a.parentNode;(d=!e)&&(e=R).appendChild(a);e=~z.qsa(e,c).indexOf(a);d&&R.removeChild(a);
return e};K=function(a){return a.replace(/-+(.)?/g,function(a,H){return H?H.toUpperCase():""})};L=function(a){return A.call(a,function(c,d){return a.indexOf(c)==d})};z.fragment=function(a,c,d){var e,n,h;J.test(a)&&(e=l(y.createElement(RegExp.$1)));e||(a.replace&&(a=a.replace(T,"<$1></$2>")),c===u&&(c=G.test(a)&&RegExp.$1),c in Q||(c="*"),h=Q[c],h.innerHTML=""+a,e=l.each(C.call(h.childNodes),function(){h.removeChild(this)}));m(d)&&(n=l(e),l.each(d,function(a,c){if(-1<V.indexOf(a))n[a](c);else n.attr(a,
c)}));return e};z.Z=function(a,c){a=a||[];a.__proto__=l.fn;a.selector=c||"";return a};z.isZ=function(a){return a instanceof z.Z};z.init=function(a,c){var d;if(a)if("string"==typeof a)if(a=a.trim(),"<"==a[0]&&G.test(a))d=z.fragment(a,RegExp.$1,c),a=null;else{if(c!==u)return l(c).find(a);d=z.qsa(y,a)}else{if(k(a))return l(y).ready(a);if(z.isZ(a))return a;if(I(a))d=w(a);else if(r(a))d=[a],a=null;else if(G.test(a))d=z.fragment(a.trim(),RegExp.$1,c),a=null;else{if(c!==u)return l(c).find(a);d=z.qsa(y,a)}}else return z.Z();
return z.Z(d,a)};l=function(a,c){return z.init(a,c)};l.extend=function(a){var c,e=C.call(arguments,1);"boolean"==typeof a&&(c=a,a=e.shift());e.forEach(function(e){d(a,e,c)});return a};z.qsa=function(a,c){var d,e="#"==c[0],n=!e&&"."==c[0],h=e||n?c.slice(1):c,f=X.test(h);return t(a)&&f&&e?(d=a.getElementById(h))?[d]:[]:1!==a.nodeType&&9!==a.nodeType?[]:C.call(f&&!e?n?a.getElementsByClassName(h):a.getElementsByTagName(c):a.querySelectorAll(c))};l.contains=y.documentElement.contains?function(a,c){return a!==
c&&a.contains(c)}:function(a,c){for(;c&&(c=c.parentNode);)if(c===a)return!0;return!1};l.type=a;l.isFunction=k;l.isWindow=g;l.isArray=I;l.isPlainObject=m;l.isEmptyObject=function(a){for(var c in a)return!1;return!0};l.inArray=function(a,c,d){return D.indexOf.call(c,a,d)};l.camelCase=K;l.trim=function(a){return null==a?"":String.prototype.trim.call(a)};l.uuid=0;l.support={};l.expr={};l.map=function(a,c){var d,e=[],n;if("number"==typeof a.length)for(n=0;n<a.length;n++)d=c(a[n],n),null!=d&&e.push(d);
else for(n in a)d=c(a[n],n),null!=d&&e.push(d);return 0<e.length?l.fn.concat.apply([],e):e};l.each=function(a,c){var d;if("number"==typeof a.length)for(d=0;d<a.length&&!1!==c.call(a[d],d,a[d]);d++);else for(d in a)if(!1===c.call(a[d],d,a[d]))break;return a};l.grep=function(a,c){return A.call(a,c)};window.JSON&&(l.parseJSON=JSON.parse);l.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,c){M["[object "+c+"]"]=c.toLowerCase()});l.fn={forEach:D.forEach,reduce:D.reduce,
push:D.push,sort:D.sort,indexOf:D.indexOf,concat:D.concat,map:function(a){return l(l.map(this,function(c,d){return a.call(c,d,c)}))},slice:function(){return l(C.apply(this,arguments))},ready:function(a){W.test(y.readyState)&&y.body?a(l):y.addEventListener("DOMContentLoaded",function(){a(l)},!1);return this},get:function(a){return a===u?C.call(this):this[0<=a?a:a+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=
this.parentNode&&this.parentNode.removeChild(this)})},each:function(a){D.every.call(this,function(c,d){return!1!==a.call(c,d,c)});return this},filter:function(a){return k(a)?this.not(this.not(a)):l(A.call(this,function(c){return z.matches(c,a)}))},add:function(a,c){return l(L(this.concat(l(a,c))))},is:function(a){return 0<this.length&&z.matches(this[0],a)},not:function(a){var c=[];if(k(a)&&a.call!==u)this.each(function(d){a.call(this,d)||c.push(this)});else{var d="string"==typeof a?this.filter(a):
"number"==typeof a.length&&k(a.item)?C.call(a):l(a);this.forEach(function(a){0>d.indexOf(a)&&c.push(a)})}return l(c)},has:function(a){return this.filter(function(){return r(a)?l.contains(this,a):l(this).find(a).size()})},eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];return a&&!r(a)?a:l(a)},last:function(){var a=this[this.length-1];return a&&!r(a)?a:l(a)},find:function(a){var c=this;return a?"object"==typeof a?l(a).filter(function(){var a=this;return D.some.call(c,
function(c){return l.contains(c,a)})}):1==this.length?l(z.qsa(this[0],a)):this.map(function(){return z.qsa(this,a)}):[]},closest:function(a,c){var d=this[0],e=!1;for("object"==typeof a&&(e=l(a));d&&!(e?0<=e.indexOf(d):z.matches(d,a));)d=d!==c&&!t(d)&&d.parentNode;return l(d)},parents:function(a){for(var c=[],d=this;0<d.length;)d=l.map(d,function(a){if((a=a.parentNode)&&!t(a)&&0>c.indexOf(a))return c.push(a),a});return h(c,a)},parent:function(a){return h(L(this.pluck("parentNode")),a)},children:function(a){return h(this.map(function(){return c(this)}),
a)},contents:function(){return this.map(function(){return C.call(this.childNodes)})},siblings:function(a){return h(this.map(function(a,d){return A.call(c(d.parentNode),function(a){return a!==d})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return l.map(this,function(c){return c[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display="");if("none"==getComputedStyle(this,"").getPropertyValue("display")){var a=this.style,
c=this.nodeName,d,e;n[c]||(d=y.createElement(c),y.body.appendChild(d),e=getComputedStyle(d,"").getPropertyValue("display"),d.parentNode.removeChild(d),"none"==e&&(e="block"),n[c]=e);a.display=n[c]}})},replaceWith:function(a){return this.before(a).remove()},wrap:function(a){var c=k(a);if(this[0]&&!c)var d=l(a).get(0),e=d.parentNode||1<this.length;return this.each(function(n){l(this).wrapAll(c?a.call(this,n):e?d.cloneNode(!0):d)})},wrapAll:function(a){if(this[0]){l(this[0]).before(a=l(a));for(var c;(c=
a.children()).length;)a=c.first();l(a).append(this)}return this},wrapInner:function(a){var c=k(a);return this.each(function(d){var e=l(this),n=e.contents();d=c?a.call(this,d):a;n.length?n.wrapAll(d):e.append(d)})},unwrap:function(){this.parent().each(function(){l(this).replaceWith(l(this).children())});return this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(a){return this.each(function(){var c=l(this);
(a===u?"none"==c.css("display"):a)?c.show():c.hide()})},prev:function(a){return l(this.pluck("previousElementSibling")).filter(a||"*")},next:function(a){return l(this.pluck("nextElementSibling")).filter(a||"*")},html:function(a){return 0 in arguments?this.each(function(c){var d=this.innerHTML;l(this).empty().append(e(this,a,c,d))}):0 in this?this[0].innerHTML:null},text:function(a){return 0 in arguments?this.each(function(c){c=e(this,a,c,this.textContent);this.textContent=null==c?"":""+c}):0 in this?
this[0].textContent:null},attr:function(a,c){var d;return"string"==typeof a&&!(1 in arguments)?!this.length||1!==this[0].nodeType?u:!(d=this[0].getAttribute(a))&&a in this[0]?this[0][a]:d:this.each(function(d){if(1===this.nodeType)if(r(a))for(s in a){var n=s;d=a[s];null==d?this.removeAttribute(n):this.setAttribute(n,d)}else n=a,d=e(this,c,d,this.getAttribute(a)),null==d?this.removeAttribute(n):this.setAttribute(n,d)})},removeAttr:function(a){return this.each(function(){1===this.nodeType&&this.removeAttribute(a)})},
prop:function(a,c){a=Y[a]||a;return 1 in arguments?this.each(function(d){this[a]=e(this,c,d,this[a])}):this[0]&&this[0][a]},data:function(a,c){var d="data-"+a.replace(U,"-$1").toLowerCase(),d=1 in arguments?this.attr(d,c):this.attr(d);return null!==d?q(d):u},val:function(a){return 0 in arguments?this.each(function(c){this.value=e(this,a,c,this.value)}):this[0]&&(this[0].multiple?l(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value)},offset:function(a){if(a)return this.each(function(c){var d=
l(this);c=e(this,a,c,d.offset());var n=d.offsetParent().offset();c={top:c.top-n.top,left:c.left-n.left};"static"==d.css("position")&&(c.position="relative");d.css(c)});if(!this.length)return null;var c=this[0].getBoundingClientRect();return{left:c.left+window.pageXOffset,top:c.top+window.pageYOffset,width:Math.round(c.width),height:Math.round(c.height)}},css:function(c,d){if(2>arguments.length){var e=this[0],n=getComputedStyle(e,"");if(!e)return;if("string"==typeof c)return e.style[K(c)]||n.getPropertyValue(c);
if(I(c)){var h={};l.each(c,function(a,c){h[c]=e.style[K(c)]||n.getPropertyValue(c)});return h}}var f="";if("string"==a(c))!d&&0!==d?this.each(function(){this.style.removeProperty(p(c))}):f=p(c)+":"+("number"==typeof d&&!F[p(c)]?d+"px":d);else for(s in c)!c[s]&&0!==c[s]?this.each(function(){this.style.removeProperty(p(s))}):f+=p(s)+":"+("number"==typeof c[s]&&!F[p(s)]?c[s]+"px":c[s])+";";return this.each(function(){this.style.cssText+=";"+f})},index:function(a){return a?this.indexOf(l(a)[0]):this.parent().children().indexOf(this[0])},
hasClass:function(a){return!a?!1:D.some.call(this,function(a){return this.test(f(a))},x(a))},addClass:function(a){return!a?this:this.each(function(c){if("className"in this){E=[];var d=f(this);e(this,a,c,d).split(/\s+/g).forEach(function(a){l(this).hasClass(a)||E.push(a)},this);E.length&&f(this,d+(d?" ":"")+E.join(" "))}})},removeClass:function(a){return this.each(function(c){if("className"in this){if(a===u)return f(this,"");E=f(this);e(this,a,c,E).split(/\s+/g).forEach(function(a){E=E.replace(x(a),
" ")});f(this,E.trim())}})},toggleClass:function(a,c){return!a?this:this.each(function(d){var n=l(this);e(this,a,d,f(this)).split(/\s+/g).forEach(function(a){(c===u?!n.hasClass(a):c)?n.addClass(a):n.removeClass(a)})})},scrollTop:function(a){if(this.length){var c="scrollTop"in this[0];return a===u?c?this[0].scrollTop:this[0].pageYOffset:this.each(c?function(){this.scrollTop=a}:function(){this.scrollTo(this.scrollX,a)})}},scrollLeft:function(a){if(this.length){var c="scrollLeft"in this[0];return a===
u?c?this[0].scrollLeft:this[0].pageXOffset:this.each(c?function(){this.scrollLeft=a}:function(){this.scrollTo(a,this.scrollY)})}},position:function(){if(this.length){var a=this[0],c=this.offsetParent(),d=this.offset(),e=O.test(c[0].nodeName)?{top:0,left:0}:c.offset();d.top-=parseFloat(l(a).css("margin-top"))||0;d.left-=parseFloat(l(a).css("margin-left"))||0;e.top+=parseFloat(l(c[0]).css("border-top-width"))||0;e.left+=parseFloat(l(c[0]).css("border-left-width"))||0;return{top:d.top-e.top,left:d.left-
e.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||y.body;a&&!O.test(a.nodeName)&&"static"==l(a).css("position");)a=a.offsetParent;return a})}};l.fn.detach=l.fn.remove;["width","height"].forEach(function(a){var c=a.replace(/./,function(a){return a[0].toUpperCase()});l.fn[a]=function(d){var n,h=this[0];return d===u?g(h)?h["inner"+c]:t(h)?h.documentElement["scroll"+c]:(n=this.offset())&&n[a]:this.each(function(c){h=l(this);h.css(a,e(this,d,c,h[a]()))})}});["after",
"prepend","before","append"].forEach(function(c,d){var e=d%2;l.fn[c]=function(){var c,n=l.map(arguments,function(d){c=a(d);return"object"==c||"array"==c||null==d?d:z.fragment(d)}),h,f=1<this.length;return 1>n.length?this:this.each(function(a,c){h=e?c:c.parentNode;c=0==d?c.nextSibling:1==d?c.firstChild:2==d?c:null;var B=l.contains(y.documentElement,h);n.forEach(function(a){if(f)a=a.cloneNode(!0);else if(!h)return l(a).remove();h.insertBefore(a,c);B&&v(a,function(a){null!=a.nodeName&&"SCRIPT"===a.nodeName.toUpperCase()&&
((!a.type||"text/javascript"===a.type)&&!a.src)&&window.eval.call(window,a.innerHTML)})})})};l.fn[e?c+"To":"insert"+(d?"Before":"After")]=function(a){l(a)[c](this);return this}});z.Z.prototype=l.fn;z.uniq=L;z.deserializeValue=q;l.zepto=z;return l}();window.Zepto=Zepto;void 0===window.$&&(window.$=Zepto);
(function(a){"__proto__"in{}||a.extend(a.zepto,{Z:function(g,k){g=g||[];a.extend(g,a.fn);g.selector=k||"";g.__Z=!0;return g},isZ:function(g){return"array"===a.type(g)&&"__Z"in g}});try{getComputedStyle(void 0)}catch(k){var g=getComputedStyle;window.getComputedStyle=function(a){try{return g(a)}catch(k){return null}}}})(Zepto);
(function(a){function k(c){c=a(c);return!(!c.width()&&!c.height())&&"none"!==c.css("display")}function g(a,c){a=a.replace(/=#\]/g,'="#"]');var e,f,g=p.exec(a);g&&g[2]in w&&(e=w[g[2]],f=g[3],a=g[1],f&&(g=Number(f),f=isNaN(g)?f.replace(/^["']|["']$/g,""):g));return c(a,e,f)}var t=a.zepto,r=t.qsa,m=t.matches,w=a.expr[":"]={visible:function(){if(k(this))return this},hidden:function(){if(!k(this))return this},selected:function(){if(this.selected)return this},checked:function(){if(this.checked)return this},
parent:function(){return this.parentNode},first:function(a){if(0===a)return this},last:function(a,c){if(a===c.length-1)return this},eq:function(a,c,e){if(a===e)return this},contains:function(c,h,e){if(-1<a(this).text().indexOf(e))return this},has:function(a,c,e){if(t.qsa(this,e).length)return this}},p=/(.*):(\w+)(?:\(([^)]+)\))?$\s*/,x=/^\s*>/,c="Zepto"+ +new Date;t.qsa=function(d,h){return g(h,function(e,f,g){try{var k;!e&&f?e="*":x.test(e)&&(k=a(d).addClass(c),e="."+c+" "+e);var m=r(d,e)}catch(s){throw console.error("error performing selector: %o",
h),s;}finally{k&&k.removeClass(c)}return!f?m:t.uniq(a.map(m,function(a,c){return f.call(a,c,m,g)}))})};t.matches=function(a,c){return g(c,function(c,h,g){return(!c||m(a,c))&&(!h||h.call(a,null,g)===a)})}})(Zepto);
(function(a){a.fn.end=function(){return this.prevObject||a()};a.fn.andSelf=function(){return this.add(this.prevObject||a())};"filter add not eq first last find closest parents parent children siblings".split(" ").forEach(function(k){var g=a.fn[k];a.fn[k]=function(){var a=g.apply(this,arguments);a.prevObject=this;return a}})})(Zepto);
(function(a){function k(a){return a._zid||(a._zid=x++)}function g(a,c,d,e){c=t(c);if(c.ns)var h=RegExp("(?:^| )"+c.ns.replace(" "," .* ?")+"(?: |$)");return(f[k(a)]||[]).filter(function(a){return a&&(!c.e||a.e==c.e)&&(!c.ns||h.test(a.ns))&&(!d||k(a.fn)===k(d))&&(!e||a.sel==e)})}function t(a){a=(""+a).split(".");return{e:a[0],ns:a.slice(1).sort().join(" ")}}function r(d,e,n,h,g,l,m){var p=k(d),r=f[p]||(f[p]=[]);e.split(/\s/).forEach(function(e){if("ready"==e)return a(document).ready(n);var f=t(e);
f.fn=n;f.sel=g;f.e in s&&(n=function(c){var d=c.relatedTarget;if(!d||d!==this&&!a.contains(this,d))return f.fn.apply(this,arguments)});var k=(f.del=l)||n;f.proxy=function(a){a=w(a);if(!a.isImmediatePropagationStopped()){a.data=h;var e=k.apply(d,a._args==c?[a]:[a].concat(a._args));!1===e&&(a.preventDefault(),a.stopPropagation());return e}};f.i=r.length;r.push(f);"addEventListener"in d&&d.addEventListener(s[f.e]||v&&u[f.e]||f.e,f.proxy,f.del&&!v&&f.e in u||!!m)})}function m(a,c,d,e,h){var l=k(a);(c||
"").split(/\s/).forEach(function(c){g(a,c,d,e).forEach(function(c){delete f[l][c.i];"removeEventListener"in a&&a.removeEventListener(s[c.e]||v&&u[c.e]||c.e,c.proxy,c.del&&!v&&c.e in u||!!h)})})}function w(d,e){if(e||!d.isDefaultPrevented)if(e||(e=d),a.each(C,function(a,c){var h=e[a];d[a]=function(){this[c]=l;return h&&h.apply(e,arguments)};d[c]=E}),e.defaultPrevented!==c?e.defaultPrevented:"returnValue"in e?!1===e.returnValue:e.getPreventDefault&&e.getPreventDefault())d.isDefaultPrevented=l;return d}
function p(a){var d,e={originalEvent:a};for(d in a)!D.test(d)&&a[d]!==c&&(e[d]=a[d]);return w(e,a)}var x=1,c,d=Array.prototype.slice,h=a.isFunction,e=function(a){return"string"==typeof a},f={},q={},v="onfocusin"in window,u={focus:"focusin",blur:"focusout"},s={mouseenter:"mouseover",mouseleave:"mouseout"};q.click=q.mousedown=q.mouseup=q.mousemove="MouseEvents";a.event={add:r,remove:m};a.proxy=function(c,f){var n=2 in arguments&&d.call(arguments,2);if(h(c)){var g=function(){return c.apply(f,n?n.concat(d.call(arguments)):
arguments)};g._zid=k(c);return g}if(e(f))return n?(n.unshift(c[f],c),a.proxy.apply(null,n)):a.proxy(c[f],c);throw new TypeError("expected function");};a.fn.bind=function(a,c,d){return this.on(a,c,d)};a.fn.unbind=function(a,c){return this.off(a,c)};a.fn.one=function(a,c,d,e){return this.on(a,c,d,e,1)};var l=function(){return!0},E=function(){return!1},D=/^([A-Z]|returnValue$|layer[XY]$)/,C={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};
a.fn.delegate=function(a,c,d){return this.on(c,a,d)};a.fn.undelegate=function(a,c,d){return this.off(c,a,d)};a.fn.live=function(c,d){a(document.body).delegate(this.selector,c,d);return this};a.fn.die=function(c,d){a(document.body).undelegate(this.selector,c,d);return this};a.fn.on=function(f,g,n,B,l){var k,s,u=this;if(f&&!e(f))return a.each(f,function(a,c){u.on(a,g,n,c,l)}),u;!e(g)&&!h(B)&&!1!==B&&(B=n,n=g,g=c);if(h(n)||!1===n)B=n,n=c;!1===B&&(B=E);return u.each(function(c,e){l&&(k=function(a){m(e,
a.type,B);return B.apply(this,arguments)});g&&(s=function(c){var n,f=a(c.target).closest(g,e).get(0);if(f&&f!==e)return n=a.extend(p(c),{currentTarget:f,liveFired:e}),(k||B).apply(f,[n].concat(d.call(arguments,1)))});r(e,f,B,n,g,s||k)})};a.fn.off=function(d,f,n){var g=this;if(d&&!e(d))return a.each(d,function(a,c){g.off(a,f,c)}),g;!e(f)&&!h(n)&&!1!==n&&(n=f,f=c);!1===n&&(n=E);return g.each(function(){m(this,d,n,f)})};a.fn.trigger=function(c,d){c=e(c)||a.isPlainObject(c)?a.Event(c):w(c);c._args=d;
return this.each(function(){"dispatchEvent"in this?this.dispatchEvent(c):a(this).triggerHandler(c,d)})};a.fn.triggerHandler=function(c,d){var f,h;this.each(function(l,k){f=p(e(c)?a.Event(c):c);f._args=d;f.target=k;a.each(g(k,c.type||c),function(a,c){h=c.proxy(f);if(f.isImmediatePropagationStopped())return!1})});return h};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(c){a.fn[c]=
function(a){return a?this.bind(c,a):this.trigger(c)}});["focus","blur"].forEach(function(c){a.fn[c]=function(a){a?this.bind(c,a):this.each(function(){try{this[c]()}catch(a){}});return this}});a.Event=function(a,c){e(a)||(c=a,a=c.type);var d=document.createEvent(q[a]||"Events"),f=!0;if(c)for(var h in c)"bubbles"==h?f=!!c[h]:d[h]=c[h];d.initEvent(a,f,!0);return w(d)}})(Zepto);
(function(a){function k(c,d){var h=c[p],h=h&&r[h];if(void 0===d)return h||g(c);if(h){if(d in h)return h[d];var e=w(d);if(e in h)return h[e]}return m.call(a(c),d)}function g(c,d,h){var e=c[p]||(c[p]=++a.uuid);c=r[e]||(r[e]=t(c));void 0!==d&&(c[w(d)]=h);return c}function t(c){var d={};a.each(c.attributes||x,function(c,e){0==e.name.indexOf("data-")&&(d[w(e.name.replace("data-",""))]=a.zepto.deserializeValue(e.value))});return d}var r={},m=a.fn.data,w=a.camelCase,p=a.expando="Zepto"+ +new Date,x=[];a.fn.data=
function(c,d){return void 0===d?a.isPlainObject(c)?this.each(function(d,e){a.each(c,function(a,c){g(e,a,c)})}):0 in this?k(this[0],c):void 0:this.each(function(){g(this,c,d)})};a.fn.removeData=function(c){"string"==typeof c&&(c=c.split(/\s+/));return this.each(function(){var d=this[p],h=d&&r[d];h&&a.each(c||h,function(a){delete h[c?w(this):a]})})};["remove","empty"].forEach(function(c){var d=a.fn[c];a.fn[c]=function(){var a=this.find("*");"remove"===c&&(a=a.add(this));a.removeData();return d.call(this)}})})(Zepto);
(function(a){function k(c,d,e,f){if(c.global)return c=d||q,e=a.Event(e),a(c).trigger(e,f),!e.isDefaultPrevented()}function g(c){c.global&&0===a.active++&&k(c,null,"ajaxStart")}function t(a,c){var d=c.context;if(!1===c.beforeSend.call(d,a,c)||!1===k(c,d,"ajaxBeforeSend",[a,c]))return!1;k(c,d,"ajaxSend",[a,c])}function r(a,c,d,e){var f=d.context;d.success.call(f,a,"success",c);e&&e.resolveWith(f,[a,"success",c]);k(d,f,"ajaxSuccess",[c,d,a]);w("success",c,d)}function m(a,c,d,e,f){var h=e.context;e.error.call(h,
d,c,a);f&&f.rejectWith(h,[d,c,a]);k(e,h,"ajaxError",[d,e,a||c]);w(c,d,e)}function w(c,d,e){var f=e.context;e.complete.call(f,d,c);k(e,f,"ajaxComplete",[d,e]);e.global&&!--a.active&&k(e,null,"ajaxStop")}function p(){}function x(a){a&&(a=a.split(";",2)[0]);return a&&(a==C?"html":a==D?"json":l.test(a)?"script":E.test(a)&&"xml")||"text"}function c(a,c){return""==c?a:(a+"&"+c).replace(/[&?]{1,2}/,"?")}function d(d){d.processData&&d.data&&"string"!=a.type(d.data)&&(d.data=a.param(d.data,d.traditional));
if(d.data&&(!d.type||"GET"==d.type.toUpperCase()))d.url=c(d.url,d.data),d.data=void 0}function h(c,d,e,f){a.isFunction(d)&&(f=e,e=d,d=void 0);a.isFunction(e)||(f=e,e=void 0);return{url:c,data:d,success:e,dataType:f}}function e(c,d,f,h){var g,l=a.isArray(d),k=a.isPlainObject(d);a.each(d,function(d,m){g=a.type(m);h&&(d=f?h:h+"["+(k||"object"==g||"array"==g?d:"")+"]");!h&&l?c.add(m.name,m.value):"array"==g||!f&&"object"==g?e(c,m,f,d):c.add(d,m)})}var f=0,q=window.document,v,u,s=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
l=/^(?:text|application)\/javascript/i,E=/^(?:text|application)\/xml/i,D="application/json",C="text/html",A=/^\s*$/;a.active=0;a.ajaxJSONP=function(c,d){if(!("type"in c))return a.ajax(c);var e=c.jsonpCallback,h=(a.isFunction(e)?e():e)||"jsonp"+ ++f,g=q.createElement("script"),l=window[h],k,s=function(c){a(g).triggerHandler("error",c||"abort")},p={abort:s},u;d&&d.promise(p);a(g).on("load error",function(e,f){clearTimeout(u);a(g).off().remove();"error"==e.type||!k?m(null,f||"error",p,c,d):r(k[0],p,
c,d);window[h]=l;k&&a.isFunction(l)&&l(k[0]);l=k=void 0});if(!1===t(p,c))return s("abort"),p;window[h]=function(){k=arguments};g.src=c.url.replace(/\?(.+)=\?/,"?$1="+h);q.head.appendChild(g);0<c.timeout&&(u=setTimeout(function(){s("timeout")},c.timeout));return p};a.ajaxSettings={type:"GET",beforeSend:p,success:p,error:p,complete:p,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript, application/x-javascript",json:D,xml:"application/xml, text/xml",
html:C,text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};a.ajax=function(e){var f=a.extend({},e||{}),h=a.Deferred&&a.Deferred();for(v in a.ajaxSettings)void 0===f[v]&&(f[v]=a.ajaxSettings[v]);g(f);f.crossDomain||(f.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(f.url)&&RegExp.$2!=window.location.host);f.url||(f.url=window.location.toString());d(f);var l=f.dataType,k=/\?.+=\?/.test(f.url);k&&(l="jsonp");if(!1===f.cache||(!e||!0!==e.cache)&&("script"==l||"jsonp"==l))f.url=c(f.url,"_="+
Date.now());if("jsonp"==l)return k||(f.url=c(f.url,f.jsonp?f.jsonp+"=?":!1===f.jsonp?"":"callback=?")),a.ajaxJSONP(f,h);e=f.accepts[l];var s={},k=function(a,c){s[a.toLowerCase()]=[a,c]},w=/^([\w-]+:)\/\//.test(f.url)?RegExp.$1:window.location.protocol,q=f.xhr(),D=q.setRequestHeader,y;h&&h.promise(q);f.crossDomain||k("X-Requested-With","XMLHttpRequest");k("Accept",e||"*/*");if(e=f.mimeType||e)-1<e.indexOf(",")&&(e=e.split(",",2)[0]),q.overrideMimeType&&q.overrideMimeType(e);if(f.contentType||!1!==
f.contentType&&f.data&&"GET"!=f.type.toUpperCase())k("Content-Type",f.contentType||"application/x-www-form-urlencoded");if(f.headers)for(u in f.headers)k(u,f.headers[u]);q.setRequestHeader=k;q.onreadystatechange=function(){if(4==q.readyState){q.onreadystatechange=p;clearTimeout(y);var c,d=!1;if(200<=q.status&&300>q.status||304==q.status||0==q.status&&"file:"==w){l=l||x(f.mimeType||q.getResponseHeader("content-type"));c=q.responseText;try{"script"==l?(0,eval)(c):"xml"==l?c=q.responseXML:"json"==l&&
(c=A.test(c)?null:a.parseJSON(c))}catch(e){d=e}d?m(d,"parsererror",q,f,h):r(c,q,f,h)}else m(q.statusText||null,q.status?"error":"abort",q,f,h)}};if(!1===t(q,f))return q.abort(),m(null,"abort",q,f,h),q;if(f.xhrFields)for(u in f.xhrFields)q[u]=f.xhrFields[u];q.open(f.type,f.url,"async"in f?f.async:!0,f.username,f.password);for(u in s)D.apply(q,s[u]);0<f.timeout&&(y=setTimeout(function(){q.onreadystatechange=p;q.abort();m(null,"timeout",q,f,h)},f.timeout));q.send(f.data?f.data:null);return q};a.get=
function(){return a.ajax(h.apply(null,arguments))};a.post=function(){var c=h.apply(null,arguments);c.type="POST";return a.ajax(c)};a.getJSON=function(){var c=h.apply(null,arguments);c.dataType="json";return a.ajax(c)};a.fn.load=function(c,d,e){if(!this.length)return this;var f=this,g=c.split(/\s/),l;c=h(c,d,e);var k=c.success;1<g.length&&(c.url=g[0],l=g[1]);c.success=function(c){f.html(l?a("<div>").html(c.replace(s,"")).find(l):c);k&&k.apply(f,arguments)};a.ajax(c);return this};var y=encodeURIComponent;
a.param=function(a,c){var d=[];d.add=function(a,c){this.push(y(a)+"="+y(c))};e(d,a,c);return d.join("&").replace(/%20/g,"+")}})(Zepto);
(function(a){a.fn.serializeArray=function(){var k,g,t=[];a([].slice.call(this.get(0).elements)).each(function(){k=a(this);g=k.attr("type");this.name&&"fieldset"!=this.nodeName.toLowerCase()&&(!this.disabled&&"submit"!=g&&"reset"!=g&&"button"!=g&&("radio"!=g&&"checkbox"!=g||this.checked))&&t.push({name:k.attr("name"),value:k.val()})});return t};a.fn.serialize=function(){var a=[];this.serializeArray().forEach(function(g){a.push(encodeURIComponent(g.name)+"="+encodeURIComponent(g.value))});return a.join("&")};
a.fn.submit=function(k){k?this.bind("submit",k):this.length&&(k=a.Event("submit"),this.eq(0).trigger(k),k.isDefaultPrevented()||this.get(0).submit());return this}})(Zepto);
(function(a,k){var g="",t,r=window.document.createElement("div"),m=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i,w,p,x,c,d,h,e,f,q,v={};a.each({Webkit:"webkit",Moz:"",O:"o"},function(a,c){if(r.style[a+"TransitionProperty"]!==k)return g="-"+a.toLowerCase()+"-",t=c,!1});w=g+"transform";v[p=g+"transition-property"]=v[x=g+"transition-duration"]=v[d=g+"transition-delay"]=v[c=g+"transition-timing-function"]=v[h=g+"animation-name"]=v[e=g+"animation-duration"]=v[q=g+"animation-delay"]=
v[f=g+"animation-timing-function"]="";a.fx={off:t===k&&r.style.transitionProperty===k,speeds:{_default:400,fast:200,slow:600},cssPrefix:g,transitionEnd:t?t+"TransitionEnd":"transitionend",animationEnd:t?t+"AnimationEnd":"animationend"};a.fn.animate=function(c,d,e,f,h){a.isFunction(d)&&(f=d,d=e=k);a.isFunction(e)&&(f=e,e=k);a.isPlainObject(d)&&(e=d.easing,f=d.complete,h=d.delay,d=d.duration);d&&(d=("number"==typeof d?d:a.fx.speeds[d]||a.fx.speeds._default)/1E3);h&&(h=parseFloat(h)/1E3);return this.anim(c,
d,e,f,h)};a.fn.anim=function(g,s,l,r,t){var C,A={},y,n="",B=this,F,G=a.fx.transitionEnd,J=!1;s===k&&(s=a.fx.speeds._default/1E3);t===k&&(t=0);a.fx.off&&(s=0);if("string"==typeof g)A[h]=g,A[e]=s+"s",A[q]=t+"s",A[f]=l||"linear",G=a.fx.animationEnd;else{y=[];for(C in g)m.test(C)?n+=C+"("+g[C]+") ":(A[C]=g[C],y.push(C.replace(/([a-z])([A-Z])/,"$1-$2").toLowerCase()));n&&(A[w]=n,y.push(w));0<s&&"object"===typeof g&&(A[p]=y.join(", "),A[x]=s+"s",A[d]=t+"s",A[c]=l||"linear")}F=function(c){if("undefined"!==
typeof c){if(c.target!==c.currentTarget)return;a(c.target).unbind(G,F)}else a(this).unbind(G,F);J=!0;a(this).css(v);r&&r.call(this)};0<s&&(this.bind(G,F),setTimeout(function(){J||F.call(B)},1E3*s+25));this.size()&&this.get(0).clientLeft;this.css(A);0>=s&&setTimeout(function(){B.each(function(){F.call(this)})},0);return this};r=null})(Zepto);
(function(a,k){function g(g,m,c,d,h){"function"==typeof m&&!h&&(h=m,m=k);c={opacity:c};d&&(c.scale=d,g.css(a.fx.cssPrefix+"transform-origin","0 0"));return g.animate(c,m,null,h)}function t(k,r,c,d){return g(k,r,0,c,function(){m.call(a(this));d&&d.call(this)})}var r=a.fn.show,m=a.fn.hide,w=a.fn.toggle;a.fn.show=function(a,m){r.call(this);a===k?a=0:this.css("opacity",0);return g(this,a,1,"1,1",m)};a.fn.hide=function(a,g){return a===k?m.call(this):t(this,a,"0,0",g)};a.fn.toggle=function(g,m){return g===
k||"boolean"==typeof g?w.call(this,g):this.each(function(){var c=a(this);c["none"==c.css("display")?"show":"hide"](g,m)})};a.fn.fadeTo=function(a,k,c){return g(this,a,k,null,c)};a.fn.fadeIn=function(a,g){var c=this.css("opacity");0<c?this.css("opacity",0):c=1;return r.call(this).fadeTo(a,c,g)};a.fn.fadeOut=function(a,g){return t(this,a,null,g)};a.fn.fadeToggle=function(g,k){return this.each(function(){var c=a(this);c[0==c.css("opacity")||"none"==c.css("display")?"fadeIn":"fadeOut"](g,k)})}})(Zepto);
(function(a){function k(){c=null;m.last&&(m.el.trigger("longTap"),m={})}function g(){w&&clearTimeout(w);p&&clearTimeout(p);x&&clearTimeout(x);c&&clearTimeout(c);w=p=x=c=null;m={}}function t(a){return("touch"==a.pointerType||a.pointerType==a.MSPOINTER_TYPE_TOUCH)&&a.isPrimary}function r(a,c){return a.type=="pointer"+c||a.type.toLowerCase()=="mspointer"+c}var m={},w,p,x,c,d;a(document).ready(function(){var h,e,f=0,q=0,v,u;"MSGesture"in window&&(d=new MSGesture,d.target=document.body);a(document).bind("MSGestureEnd",
function(a){if(a=1<a.velocityX?"Right":-1>a.velocityX?"Left":1<a.velocityY?"Down":-1>a.velocityY?"Up":null)m.el.trigger("swipe"),m.el.trigger("swipe"+a)}).on("touchstart MSPointerDown pointerdown",function(f){if(!(u=r(f,"down"))||t(f))v=u?f:f.touches[0],f.touches&&1===f.touches.length&&m.x2&&(m.x2=void 0,m.y2=void 0),h=Date.now(),e=h-(m.last||h),m.el=a("tagName"in v.target?v.target:v.target.parentNode),w&&clearTimeout(w),m.x1=v.pageX,m.y1=v.pageY,0<e&&250>=e&&(m.isDoubleTap=!0),m.last=h,c=setTimeout(k,
750),d&&u&&d.addPointer(f.pointerId)}).on("touchmove MSPointerMove pointermove",function(a){if(!(u=r(a,"move"))||t(a))v=u?a:a.touches[0],c&&clearTimeout(c),c=null,m.x2=v.pageX,m.y2=v.pageY,f+=Math.abs(m.x1-m.x2),q+=Math.abs(m.y1-m.y2)}).on("touchend MSPointerUp pointerup",function(d){if(!(u=r(d,"up"))||t(d))c&&clearTimeout(c),c=null,m.x2&&30<Math.abs(m.x1-m.x2)||m.y2&&30<Math.abs(m.y1-m.y2)?x=setTimeout(function(){m.el.trigger("swipe");m.el.trigger("swipe"+(Math.abs(m.x1-m.x2)>=Math.abs(m.y1-m.y2)?
0<m.x1-m.x2?"Left":"Right":0<m.y1-m.y2?"Up":"Down"));m={}},0):"last"in m&&(30>f&&30>q?p=setTimeout(function(){var c=a.Event("tap");c.cancelTouch=g;m.el.trigger(c);m.isDoubleTap?(m.el&&m.el.trigger("doubleTap"),m={}):w=setTimeout(function(){w=null;m.el&&m.el.trigger("singleTap");m={}},250)},0):m={}),f=q=0}).on("touchcancel MSPointerCancel pointercancel",g);a(window).on("scroll",g)});"swipe swipeLeft swipeRight swipeUp swipeDown doubleTap tap singleTap longTap".split(" ").forEach(function(c){a.fn[c]=
function(a){return this.on(c,a)}})})(Zepto);(function(a,k){var g=window.KingSoft=window.K||{},t=document.createElement("div").style,r={};window.K=g;g.supports=g.supports||r;var m=g.camelCase=function(a){return a.replace(/^-ms-/,"ms-").replace(/-([a-z]|[0-9])/ig,function(a,c){return(c+"").toUpperCase()})};g.uncamelCase=function(a){return a.replace(/([A-Z]|^ms)/g,"-$1").toLowerCase()};var w=g.cssVendor=function(){var a=["-webkit-","-moz-","-ms-",""],d=0;do if(m(a[d]+"transform")in t)return a[d];while(++d<a.length);return""}();g.transitionend=
{"-webkit-":"webkitTransitionEnd","-moz-":"transitionend","-ms-":"MSTransitionEnd","":"transitionend"}[w];var p=g.isCSS=function(a){var d=m(a);a=m(w+a);return d in t&&d||a in t&&a||""};g.isArrayLike=function(a){var d=g.type(a);return!!a&&"function"!=d&&"string"!=d&&(0===a.length||a.length&&a.length-1 in a)};var x=g.type=function(){for(var a="Boolean Number String Function Array Date RegExp Object Error Undefined Null".split(" "),d=0,h={};d<a.length;)g["is"+a[d]]=function(){var e=a[d].toLowerCase();
return function(a){return x(a)===e}}(),h["[object "+a[d]+"]"]=a[d++].toLowerCase();return function(a){return null==a?String(a):"object"==typeof a?h[h.toString.call(a)]||"object":typeof a}}();g.getQueryValue=function(a,d){var g=decodeURIComponent(d||location.search).match(RegExp(a+"=([^&]*)"));return g&&g[1]||""};g.getAbsUrl=function(a){var d=document.createElement("a");d.href=a;return/^http/i.test(d.href)?d.href:d.getAttribute("href",4)};g.htmlencode=function(a){return String(a).replace(/&(?![\w#]+;)|[<>"']/g,
function(a){return{"<":"&#60;",">":"&#62;",'"':"&#34;","'":"&#39;","&":"&#38;"}[a]||""})};a.each("transform transition animation perspective border-image border-radius box-shadow background-size background-clip text-shadow min-height opacity".split(" "),function(a,d){r[m(d)]=!!p(d)});r.touch="createTouch"in document||"ontouchstart"in window;r.canvas="function"==typeof document.createElement("canvas").getContext;r.svg=!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg",
"svg").createSVGRect;g.transform=p("transform");g.transition=p("transition");g.animation=p("animation");g.EVENTS="PointerEvent"in window?"pointerdown pointermove pointerup pointercancel":r.touch?"touchstart touchmove touchend touchcancel":"mousedown mousemove mouseup";r.touch||a(document).click(function(c){var d=a.Event("tap");a(c.target||c.srcElement).trigger(d)});g.Panel=createClass(function(){this.zIndex=this.constructor.prototype.zIndex++;this.mask=a('<div class="Mask" style="z-index:'+this.zIndex+
';"></div>');this.frame=a('<div class="Panel" style="z-index:'+this.zIndex+';"></div>')},{zIndex:100,setContent:function(a){this.frame.html(a);return this},show:function(c){a.contains(document.body,this.frame[0])||(this.mask.appendTo("body"),this.frame.appendTo("body"));this.frame.fadeIn(400,c);this.mask.fadeIn(400);return this},hide:function(a){this.frame.fadeOut(400,a);this.mask.fadeOut(400);return this},destroy:function(a){this.hide(function(){this.frame.remove();this.mask.remove();a&&a()}.bind(this))}});
a.ajaxSettings.cache=!1;a.ajaxSettings.dataType="json";a.ajaxSettings.type="POST";g.alert=function(a){var d=g.Panel().setContent('<a class="close"></a><div class="text">'+a+"</div>");d.frame.addClass("syswin").find(".close").tap(function(){d.destroy()});d.mask.tap(function(){d.destroy()});d.show()};a(document).on("click","[trace]",function(c){var d=this.nodeName.toLowerCase(),g=a(this),e=g.attr("trace").split(/,\s*/g),f=this.href||"";_hmt.push(["_trackEvent"].concat(e,1));"a"==d&&("_blank"!=g.attr("target")&&
f&&!/^javascript/i.test(f))&&setTimeout(function(){location.href=f},150);c.preventDefault()});Share.init({gzh:"liebao_zhushou"}).update({title:"\u55e8\uff0c2015\u4f60\u60f3\u8981\u4ec0\u4e48\u793c\u7269",desc:"\u55e8\uff0c2015\u4f60\u60f3\u8981\u4ec0\u4e48\u793c\u7269\uff0c\u753b\u4ec0\u4e48\u6709\u4ec0\u4e48\u54e6\uff0c\u65b0\u5e74\u793c\u7269\u7b49\u4f60\u62ff~",success:function(a){location.href="http://mp.weixin.qq.com/s?__biz=MjM5ODY4NTQwNA==&mid=204592543&idx=1&sn=b0b52ae3233bfbfbd64be1f5f97d4611#rd"},
img:g.getAbsUrl("images/wx.jpg"),url:g.getAbsUrl("./")})})(Zepto);
