/*!
 * Author: liujiaqi@cmcm.com
 * Date: 2015-06-21 16:56:08
 *
 * include "createClass.js"
 * include "storage.js"
 * include "lazyload.js"
 * include "sketch.js"
 * include "share.js"
 * include "zepto.min.js"
 * include "common.js"
 */
!function(a,g,l){function s(a,d){for(var h=0,f=a.length,e=[],q;h<f;h++)"undefined"!==typeof(q=d(a[h],h,a))&&e.push(q);return e}function r(a,d,h,f,e){return function(){var q=this._super,m=0,t;if(h[e]){a:{t=arguments.callee.caller;var u;if(t)for(u in f)if(f[u]===t){t=!0;break a}t=!1}if(t)a=h[e];else if(!n(a=f[e]||!f["private:"+e]&&this[e]))throw Error("Cant not run a private method!");}for(this._super=new Function;t=d[m++];){if(null==e){this._super=t.prototype._self||t;break}if(n(t.prototype[e])){this._super=
t.prototype[e];break}}m=a.apply(this,arguments);this._super=q;return m}}function m(){for(var a=arguments.length,d=arguments[0],h=1,f,e,q;h<a;h++)if(null!=(f=arguments[h]))for(e in f)if(d!==(q=f[e]))d[e]=q;return d}function v(a,d){var h=n(a),f=n(d);return h==f?0:h?-1:1}function n(a){return"function"==typeof a}var x=a[g]=function(){function a(e){q.apply(this,e)}function d(){return new a(arguments)}if(this instanceof x)throw new TypeError(g+" is not a constructor");var h,f,e=s(arguments,function(a){if(n(a)){var e;
a:{for(e in a.prototype){e=!0;break a}e=void 0}if(e)f||(f=a.prototype._self||a);else{h=a;return}}return a}),q=h||f||new Function,w=[],t={},u={_self_:q},k={_self:q=r(q,w,t,u),extend:function(){return m.apply(null,(this===k?[]:[this]).concat(s([{constructor:d}].concat(s(arguments,function(a){var e,c,f,q,p,z=[];if(n(a))w.push(f=a);else if(a&&"object"==typeof a){f=a;q={};for(e in f)if(f.hasOwnProperty(e)&&n(p=f[e])&&"constructor"!=e){c=e.split(":");if(1<c.length)switch(a=c.shift(),c=c.join(":"),a){case "private":z.push(e);
t[c]=p;break;case "static":z.push(e);d[c]=p;continue;default:c=e}else c=e;q[c]=r(u[e]=p,w,t,u,c)}for(;e=z.shift();)delete f[e]}return m(f,q)}),k).sort(v),function(a){var e;n(a)&&(e=new Function,e.prototype=a.prototype,a=new e);return a||e})))},isInstanceof:function(a){var e;if(!(e=this instanceof a))a:{for(var c=0,f=w.length;c<f;c++)if(e=w[c].prototype.isInstanceof,w[c]===a||e&&e.call(this,a)){e=!0;break a}e=!1}return e}};a.prototype=d.fn=d.prototype=k.extend.apply(k,e);d.extend=function(){return x.apply(null,
[].slice.call(arguments,0).concat(this))};return d}}(window,"createClass");(function(a,g,l,s){var r=a.document,m=a.localStorage||a.globalStorage&&a.globalStorage[location.hostname];g.prototype=g;var v=function(a,c){return(m?{length:0,init:function(){this.name=a?a+"/":"";this.getStorages();return this},getStorages:function(){for(var a=this.storages={},c=this.keys=[],f=0,e=m.length,q,w,t=RegExp("^"+this.name.replace(/([\.\?\+\*\[\]\(\)\^\$\/\|\\])/g,"\\$1"),"i");f<e;f++)q=m.key(f),t.test(q)&&(w=q.replace(t,""),c.push(w),a[w]=m.getItem(q));this.length=c.length;return this},
key:function(a){return this.keys[a]},getItem:function(a){return this.storages[a]},setItem:function(a,c){m.setItem(this.name+a,c);return this.getStorages()},removeItem:function(a){m.removeItem(this.name+a);return this.getStorages()},clear:function(){if(this.name)for(var a=this.length,c=0;c++<a;)this.removeItem(this.key(0));else m.clear();return this.getStorages()}}:{length:0,userData:c||r.getElementsByTagName("head")[0],init:function(){this.name=a?"_"+a:"";try{this.userData.addBehavior("#default#userdata"),
this.refresh()}catch(c){}return this},load:function(){try{this.userData.load("oXMLBranch"+this.name),this.storeNode=this.userData.xmlDocument.firstChild}catch(a){}},refresh:function(){this.load();this.length=this.storeNode.attributes.length;return this},key:function(a){this.load();return this.storeNode.attributes[a].nodeName.replace(/^_/,"")},getItem:function(a){this.load();return this.userData.getAttribute("_"+a)},setItem:function(a,c){this.load();this.userData.setAttribute("_"+a,c);return this.save()},
removeItem:function(a){this.load();this.userData.removeAttribute("_"+a);return this.save()},clear:function(){this.load();this.userData.xmlDocument.removeChild(this.storeNode);return this.save()},save:function(){this.userData.save("oXMLBranch"+this.name);return this.refresh()}}).init()},n;s={version:"2.4",constructor:g,init:function(a,c){"string"!=typeof a&&(c=a,a="");this.storage=v(a,c);return this.test()},test:function(){try{this.support=this.set("__storage__",1)&&this.remove("__storage__")}catch(a){this.support=
!1}return this},refresh:function(){this.storages=this.getStorages();return this},has:function(a){return null!=this.get(a)},get:function(a){return this.storages[a]},set:function(a,c){this.storage.setItem(a,c);return this.refresh().has(a)},remove:function(a){this.storage.removeItem(a);return!this.refresh().has(a)},clear:function(){this.storage.clear();return!this.refresh().size()},size:function(){return this.storage.length},getStorages:function(){for(var a={},c=this.storage,d=0,m=c&&c.length||0,f;d<
m;d++)f=c.key(d),a[f]=c.getItem(f);return a},key:function(a){return this.storage.key(a)}};for(n in s)g[n]=s[n];return a[l]=g.init()})(window,function(a,g){if(!(this instanceof arguments.callee))return new arguments.callee(a,g);this.init(a,g)},"storage");(function(a,g,l,s){var r=a.document,m=function(a){var f=0,d=0;if("getBoundingClientRect"in a)a=a.getBoundingClientRect(),f=a.top+x,d=a.left+c;else{f+=a.scrollTop||0;for(d+=a.scrollLeft||0;a;)d+=a.offsetLeft||0,f+=a.offsetTop||0,a=a.offsetParent}return{top:f,left:d}},v=function(e,f,d){return null==f?e.lazyData||(e.lazyData={ret:[],bind:null,timer:null,lastTime:0,tick:function(){var f=0,d=v(e),q=d.ret,h=r.documentElement,l=r.body,n=null!=e&&e==e.window;d.WST=(n?e.pageYOffset||h&&h.scrollTop||l.scrollTop:
m(e).top)||0;d.WSL=(n?e.pageXOffset||h&&h.scrollLeft||l.scrollLeft:m(e).left)||0;d.WH=(n?e.innerHeight||h&&h.clientHeight||l.clientHeight:e.clientHeight)||0;d.WW=(n?e.innerWidth||h&&h.clientWidth||l.clientWidth:e.clientWidth)||0;n&&(x=d.WST,c=d.WSL);for(;f<q.length;)q[f].check().length?f++:delete d.ret.splice(f,1)[0].checking;if(!d.ret.length){a:{try{var B=v(e,"resize");a.removeEventListener?(a.removeEventListener("resize",B,!1),e.removeEventListener("scroll",B,!1)):(a.detachEvent("onresize",B),e.detachEvent("onscroll",
B))}catch(y){f=!1;break a}f=!0}d.bind=!f}},resize:function(){var a=v(e),c=+new Date;clearTimeout(a.timer);100<c-a.lastTime?(a.lastTime=c,a.tick()):a.timer=setTimeout(a.resize,100-c+a.lastTime)}}):null==d?v(e)[f]:v(e)[f]=d},n=function(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?d[h.call(a)]||"object":typeof a},x=0,c=0;s="Boolean Number String Function Array Date RegExp Object Error".split(" ");for(var d={},h=d.toString,f=0;f<s.length;)d["[object "+s[f]+"]"]=s[f++].toLowerCase();
l.fn=l.prototype={constructor:l,length:0,splice:[].splice,dcb:function(){var a=this.getAttribute("data-original");a&&(this.src=a)},init:function(e,c,f){var d,h=n(c);if("function"==h)f=c;else if("object"==h&&(f=c.callback,d=c.container,c=c.range,this.isArrayLike(d)&&(d=d[0]),"string"==n(d)&&(d=r.getElementById(d)),null==d||1!=d.nodeType||"body"==d.nodeName.toLowerCase()||"html"==d.nodeName.toLowerCase()))d=a;this.cb=f||this.dcb;this.range=parseFloat(c)||0;this.container=d||a;return this.push(e)},push:function(e){"string"==
n(e)&&(e=r.getElementById(e));this.merge(e);if(this.length&&(e=v(this.container),this.checking||(e.ret.push(this),this.checking=!0),e.resize(),!e.bind)){var c;a:{var f=this.container;try{c=v(f,"resize"),a.addEventListener?(a.addEventListener("resize",c,!1),f.addEventListener("scroll",c,!1)):(a.attachEvent("onresize",c),f.attachEvent("onscroll",c))}catch(d){c=!1;break a}c=!0}e.bind=c}return this},isArrayLike:function(a){var c=n(a);return!!a&&"function"!=c&&"string"!=c&&(0===a.length||a.length&&a.length-
1 in a)},merge:function(a){var c=this.length,f=0;for(a=this.isArrayLike(a)?a:[a];f<a.length;)a[f]&&1==a[f].nodeType&&(this[c++]=a[f]),f++;this.length=c;return this},check:function(){for(var a=0,c=this.range,f=v(this.container),d,h;a<this.length;){d=this[a];h=m(d);var k=d,n=r.documentElement;!("none"==(k.currentStyle||getComputedStyle(k,null)||k.style).display||n!==k&&!(n.contains?n.contains(k):n.compareDocumentPosition&&n.compareDocumentPosition(b)&16))&&h.top+d.offsetHeight+c>=f.WST&&h.top-c<=f.WST+
f.WH&&h.left+d.offsetWidth+c>=f.WSL&&h.left-c<=f.WSL+f.WW?this.cb.call(this.splice(a,1)[0]):a++}return this},empty:function(){this.length=0;return this}};l.fn.init.prototype=l.fn;return a[g]=l})(window,"LazyLoad",function(a,g,l){return new arguments.callee.fn.init(a,g,l)});(function(a,g,l){function s(a){return(a+"").replace(/-([a-z]|[0-9])/ig,function(a,c){return(c+"").toUpperCase()})}function r(a){var e={},h,m;e.oldEvent=a;e.type=a.type.toLowerCase();e.eventType=x[e.type]||e.type;e.eventCode=c[e.type]||0;e.preventDefault=function(){a.preventDefault()};h=d[e.eventType];switch(e.eventType){case "mouse":case "pointer":m=a.pointerId||0;3==e.eventCode?delete h[m]:h[m]=a;e.changedPointers=[{id:m,ev:a}];break;case "touch":e.changedPointers=n.call(a.changedTouches).map(function(a){return{id:a.identifier,
ev:a}}),d[e.eventType]=h=n.call(a.touches)}if(m=h[Object.keys(h)[0]])e.clientX=m.clientX,e.clientY=m.clientY;e.length=Object.keys(h).length;return e}var m={start:1,down:1,move:2,end:3,up:3,cancel:3},v=[],n=[].slice,x={},c={},d={},h=a.devicePixelRatio||1;"function"==typeof[].forEach&&["mouse","touch","pointer","MSPointer-"].forEach(function(a){var e=/pointer/i.test(a)?"pointer":a;Object.keys(m).forEach(function(h){var n=m[h];h=s(a+h);v.push(h);d[e]={};x[h.toLowerCase()]=e;c[h.toLowerCase()]=n})});
g.prototype={constructor:g,lineWidth:5,color:"#000",erase:!1,bgcolor:"transparent",init:function(a){this.events={};this.actions=[];this.ctx=this.canvas.getContext("2d");"object"==typeof a&&"width height lineWidth color bgcolor multi".split(" ").forEach(function(c){this[c]="undefined"==typeof a[c]?this[c]:a[c]}.bind(this));v.forEach(function(a){this.canvas.addEventListener(a,this,!1)}.bind(this));var c;this.on({start:function(){this.moving||(c=[]);c[arguments[2]]={width:this.lineWidth,color:this.color,
erase:this.erase,pens:[arguments]}},move:function(){var a=c[arguments[2]];a.pens.push(arguments);this.draw({width:a.width,color:a.color,erase:a.erase,pens:a.pens.slice(-2)})},end:function(a,f,d){1<c[d].pens.length&&this.actions.push(c[d])},redraw:function(){var a=this.ctx;"transparent"!=this.bgcolor&&(a.fillStyle=this.bgcolor,a.fillRect(0,0,this.width,this.height))}}).clear()},handleEvent:function(a){var c=r(a),d=this.canvas.getBoundingClientRect();(this.multi||1>=c.length)&&c.changedPointers.forEach(function(a){var f=
a.ev.clientX-d.left,h=a.ev.clientY-d.top;switch(c.eventCode){case 1:this.pointerType||(this.pointerType=c.eventType);this.fire("start",f,h,a.id);this.moving=!0;break;case 2:this.moving&&this.pointerType==x[c.type]&&(c.preventDefault(),this.fire("move",f,h,a.id));break;case 3:this.moving&&this.pointerType==x[c.type]&&this.fire("end",f,h,a.id)}}.bind(this));this.moving&&!c.length&&(delete this.moving,delete this.pointerType)},on:function(a,c){"object"==typeof a?Object.keys(a).forEach(function(c){this.on(c,
a[c])}.bind(this)):(this.events[a]||(this.events[a]=[]),this.events[a].push(c));return this},fire:function(a){var c=[].slice.call(arguments,1);(this.events[a]||[]).forEach(function(a){"function"==typeof a&&a.apply(this,c)}.bind(this));return this},draw:function(a){var c=this.ctx;c.lineWidth=a.width;c.lineJoin=c.lineCap="round";a.erase?(c.strokeStyle="#000",c.globalCompositeOperation="destination-out"):(c.globalCompositeOperation="source-over",c.strokeStyle=a.color);c.beginPath();a.pens.forEach(function(a,
d){c[d?"lineTo":"moveTo"].apply(c,a)});c.stroke();return this},reDraw:function(){this.ctx.clearRect(0,0,this.width,this.height);this.fire("redraw");this.actions.forEach(this.draw.bind(this));return this},cancel:function(a){this.actions.splice(-(a||1));return this.reDraw()},clear:function(){this.actions.length=0;return this.reDraw()},toDataUrl:function(a){return this.canvas.toDataURL(a)},toBlob:function(){return(this.canvas.toBlob||function(c,d){if("mozGetAsFile"in this)return c(this.mozGetAsFile("blob",
d));var h=this.toDataURL(d).split(","),m=a.atob(h[1]),n=new Uint8Array(m.length),l,k;l=0;for(k=n.length;l<k;l++)n[l]=m.charCodeAt(l);c(new Blob([n.buffer],{type:d||h[0].split(/[:;]/)[1]}))}).apply(this.canvas,arguments)}};"function"==typeof Object.defineProperties&&(["width","height"].forEach(function(a){Object.defineProperty(g.prototype,a,{get:function(){return this.canvas[a]/h},set:function(c){this.canvas[a]=c*h;this.ctx.scale(h,h)},enumerable:!0})}),Object.defineProperty(g.prototype,"steps",{get:function(){return this.actions.length},
enumerable:!0}));a.Sketch=g})(window,function(a,g){if(!(this instanceof arguments.callee))return new arguments.callee(a,g);this.canvas="string"==typeof a?document.getElementById(a):a;this.init(g)});(function(a,g){a.Share={type:"pc",data:{title:document.title,img:"",desc:document.title,url:location.href,success:function(){},fail:function(){},complete:function(){}},init:function(){var a=this,g=["menu:share:appmessage","menu:share:timeline","menu:share:qq","menu:share:weiboApp"];"addEventListener"in document&&document.addEventListener("WeixinJSBridgeReady",function(){a.type="weixin";var r=new XMLHttpRequest;r.open("GET","http://cn.cmcm.com/wxjs/?type=cmcm&url="+encodeURIComponent(location.href.replace(/#.*$/,
"")),!0);r.onreadystatechange=function(){if(4==r.readyState&&200==r.status){var a=JSON.parse(r.responseText),l={verifyJsApiList:g};l.appId=a.appId;l.verifyAppId=a.appId;l.verifySignType="sha1";l.verifyTimestamp=a.timestamp+"";l.verifyNonceStr=a.nonceStr;l.verifySignature=a.signature;WeixinJSBridge.invoke("preVerifyJSAPI",l,function(a){})}};r.send();g.forEach(function(m){WeixinJSBridge.on(m,function(g){var n=a.data;g={img_url:n.img,desc:n.desc,title:n.title,link:n.url};var s;switch(m.split(":")[2]){case "appmessage":s=
"sendAppMessage";break;case "timeline":g.title=n.desc;g.desc=n.title;s="shareTimeline";break;case "qq":s="shareQQ";break;case "weiboApp":s="shareWeiboApp"}WeixinJSBridge.invoke(s,g,function(a){/\:(confirm|ok)$/i.test(a.err_msg)?n.success&&n.success(a):n.fail&&n.fail(a);n.complete&&n.complete(a)})})})},!1);if("undefined"!=typeof android||"undefined"!=typeof cm_web_app)this.type="cm",this.cmObj=window.android||window.cm_web_app;return this},update:function(a){var g=this.data,r;for(r in a)g[r]=a[r];
switch(this.type){case "cm":try{this.cmObj.updatesharedata(g.title,g.img,g.desc,g.url)}catch(m){}}},share:function(a){var g=this.data;"undefined"!=typeof a&&this.update(a);switch(this.type){case "cm":try{"function"==typeof this.cmObj.share?this.cmObj.share(1,g.url,g.title,g.desc,g.img):this.cmObj.sharescore()}catch(r){}}}}})(window);var Zepto=function(){function a(a){return null==a?String(a):M[S.call(a)]||"object"}function g(L){return"function"==a(L)}function l(a){return null!=a&&a==a.window}function s(a){return null!=a&&a.nodeType==a.DOCUMENT_NODE}function r(L){return"object"==a(L)}function m(a){return r(a)&&!l(a)&&Object.getPrototypeOf(a)==Object.prototype}function v(a){return B.call(a,function(a){return null!=a})}function n(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,
"$1_$2").replace(/_/g,"-").toLowerCase()}function x(a){return a in z?z[a]:z[a]=RegExp("(^|\\s)"+a+"(\\s|$)")}function c(a){return"children"in a?C.call(a.children):k.map(a.childNodes,function(a){if(1==a.nodeType)return a})}function d(a,c,f){for(u in c)f&&(m(c[u])||H(c[u]))?(m(c[u])&&!m(a[u])&&(a[u]={}),H(c[u])&&!H(a[u])&&(a[u]=[]),d(a[u],c[u],f)):c[u]!==t&&(a[u]=c[u])}function h(a,c){return null==c?k(a):k(a).filter(c)}function f(a,c,d,f){return g(c)?c.call(a,d,f):c}function e(a,c){var d=a.className||
"",f=d&&d.baseVal!==t;if(c===t)return f?d.baseVal:d;f?d.baseVal=c:a.className=c}function q(a){var c;try{return a?"true"==a||("false"==a?!1:"null"==a?null:!/^0/.test(a)&&!isNaN(c=Number(a))?c:/^[\[\{]/.test(a)?k.parseJSON(a):a):a}catch(d){return a}}function w(a,c){c(a);for(var d=0,f=a.childNodes.length;d<f;d++)w(a.childNodes[d],c)}var t,u,k,E,D=[],C=D.slice,B=D.filter,y=window.document,p={},z={},F={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},G=/^\s*<(\w+|!)[^>]*>/,
I=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,T=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,O=/^(?:body|html)$/i,U=/([A-Z])/g,V="val css html text data width height offset".split(" "),N=y.createElement("table"),P=y.createElement("tr"),Q={tr:y.createElement("tbody"),tbody:N,thead:N,tfoot:N,td:P,th:P,"*":y.createElement("div")},W=/complete|loaded|interactive/,X=/^[\w-]*$/,M={},S=M.toString,A={},J,K,R=y.createElement("div"),Y={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",
maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},H=Array.isArray||function(a){return a instanceof Array};A.matches=function(a,c){if(!c||!a||1!==a.nodeType)return!1;var d=a.webkitMatchesSelector||a.mozMatchesSelector||a.oMatchesSelector||a.matchesSelector;if(d)return d.call(a,c);var f;f=a.parentNode;(d=!f)&&(f=R).appendChild(a);f=~A.qsa(f,c).indexOf(a);d&&R.removeChild(a);
return f};J=function(a){return a.replace(/-+(.)?/g,function(a,c){return c?c.toUpperCase():""})};K=function(a){return B.call(a,function(c,d){return a.indexOf(c)==d})};A.fragment=function(a,c,d){var f,p,e;I.test(a)&&(f=k(y.createElement(RegExp.$1)));f||(a.replace&&(a=a.replace(T,"<$1></$2>")),c===t&&(c=G.test(a)&&RegExp.$1),c in Q||(c="*"),e=Q[c],e.innerHTML=""+a,f=k.each(C.call(e.childNodes),function(){e.removeChild(this)}));m(d)&&(p=k(f),k.each(d,function(a,c){if(-1<V.indexOf(a))p[a](c);else p.attr(a,
c)}));return f};A.Z=function(a,c){a=a||[];a.__proto__=k.fn;a.selector=c||"";return a};A.isZ=function(a){return a instanceof A.Z};A.init=function(a,c){var d;if(a)if("string"==typeof a)if(a=a.trim(),"<"==a[0]&&G.test(a))d=A.fragment(a,RegExp.$1,c),a=null;else{if(c!==t)return k(c).find(a);d=A.qsa(y,a)}else{if(g(a))return k(y).ready(a);if(A.isZ(a))return a;if(H(a))d=v(a);else if(r(a))d=[a],a=null;else if(G.test(a))d=A.fragment(a.trim(),RegExp.$1,c),a=null;else{if(c!==t)return k(c).find(a);d=A.qsa(y,a)}}else return A.Z();
return A.Z(d,a)};k=function(a,c){return A.init(a,c)};k.extend=function(a){var c,f=C.call(arguments,1);"boolean"==typeof a&&(c=a,a=f.shift());f.forEach(function(f){d(a,f,c)});return a};A.qsa=function(a,c){var d,f="#"==c[0],p=!f&&"."==c[0],e=f||p?c.slice(1):c,h=X.test(e);return s(a)&&h&&f?(d=a.getElementById(e))?[d]:[]:1!==a.nodeType&&9!==a.nodeType?[]:C.call(h&&!f?p?a.getElementsByClassName(e):a.getElementsByTagName(c):a.querySelectorAll(c))};k.contains=y.documentElement.contains?function(a,c){return a!==
c&&a.contains(c)}:function(a,c){for(;c&&(c=c.parentNode);)if(c===a)return!0;return!1};k.type=a;k.isFunction=g;k.isWindow=l;k.isArray=H;k.isPlainObject=m;k.isEmptyObject=function(a){for(var c in a)return!1;return!0};k.inArray=function(a,c,d){return D.indexOf.call(c,a,d)};k.camelCase=J;k.trim=function(a){return null==a?"":String.prototype.trim.call(a)};k.uuid=0;k.support={};k.expr={};k.map=function(a,c){var d,f=[],p;if("number"==typeof a.length)for(p=0;p<a.length;p++)d=c(a[p],p),null!=d&&f.push(d);
else for(p in a)d=c(a[p],p),null!=d&&f.push(d);return 0<f.length?k.fn.concat.apply([],f):f};k.each=function(a,c){var d;if("number"==typeof a.length)for(d=0;d<a.length&&!1!==c.call(a[d],d,a[d]);d++);else for(d in a)if(!1===c.call(a[d],d,a[d]))break;return a};k.grep=function(a,c){return B.call(a,c)};window.JSON&&(k.parseJSON=JSON.parse);k.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,c){M["[object "+c+"]"]=c.toLowerCase()});k.fn={forEach:D.forEach,reduce:D.reduce,
push:D.push,sort:D.sort,indexOf:D.indexOf,concat:D.concat,map:function(a){return k(k.map(this,function(c,d){return a.call(c,d,c)}))},slice:function(){return k(C.apply(this,arguments))},ready:function(a){W.test(y.readyState)&&y.body?a(k):y.addEventListener("DOMContentLoaded",function(){a(k)},!1);return this},get:function(a){return a===t?C.call(this):this[0<=a?a:a+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=
this.parentNode&&this.parentNode.removeChild(this)})},each:function(a){D.every.call(this,function(c,d){return!1!==a.call(c,d,c)});return this},filter:function(a){return g(a)?this.not(this.not(a)):k(B.call(this,function(c){return A.matches(c,a)}))},add:function(a,c){return k(K(this.concat(k(a,c))))},is:function(a){return 0<this.length&&A.matches(this[0],a)},not:function(a){var c=[];if(g(a)&&a.call!==t)this.each(function(d){a.call(this,d)||c.push(this)});else{var d="string"==typeof a?this.filter(a):
"number"==typeof a.length&&g(a.item)?C.call(a):k(a);this.forEach(function(a){0>d.indexOf(a)&&c.push(a)})}return k(c)},has:function(a){return this.filter(function(){return r(a)?k.contains(this,a):k(this).find(a).size()})},eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];return a&&!r(a)?a:k(a)},last:function(){var a=this[this.length-1];return a&&!r(a)?a:k(a)},find:function(a){var c=this;return a?"object"==typeof a?k(a).filter(function(){var a=this;return D.some.call(c,
function(c){return k.contains(c,a)})}):1==this.length?k(A.qsa(this[0],a)):this.map(function(){return A.qsa(this,a)}):[]},closest:function(a,c){var d=this[0],f=!1;for("object"==typeof a&&(f=k(a));d&&!(f?0<=f.indexOf(d):A.matches(d,a));)d=d!==c&&!s(d)&&d.parentNode;return k(d)},parents:function(a){for(var c=[],d=this;0<d.length;)d=k.map(d,function(a){if((a=a.parentNode)&&!s(a)&&0>c.indexOf(a))return c.push(a),a});return h(c,a)},parent:function(a){return h(K(this.pluck("parentNode")),a)},children:function(a){return h(this.map(function(){return c(this)}),
a)},contents:function(){return this.map(function(){return C.call(this.childNodes)})},siblings:function(a){return h(this.map(function(a,d){return B.call(c(d.parentNode),function(a){return a!==d})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return k.map(this,function(c){return c[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display="");if("none"==getComputedStyle(this,"").getPropertyValue("display")){var a=this.style,
c=this.nodeName,d,f;p[c]||(d=y.createElement(c),y.body.appendChild(d),f=getComputedStyle(d,"").getPropertyValue("display"),d.parentNode.removeChild(d),"none"==f&&(f="block"),p[c]=f);a.display=p[c]}})},replaceWith:function(a){return this.before(a).remove()},wrap:function(a){var c=g(a);if(this[0]&&!c)var d=k(a).get(0),f=d.parentNode||1<this.length;return this.each(function(p){k(this).wrapAll(c?a.call(this,p):f?d.cloneNode(!0):d)})},wrapAll:function(a){if(this[0]){k(this[0]).before(a=k(a));for(var c;(c=
a.children()).length;)a=c.first();k(a).append(this)}return this},wrapInner:function(a){var c=g(a);return this.each(function(d){var f=k(this),p=f.contents();d=c?a.call(this,d):a;p.length?p.wrapAll(d):f.append(d)})},unwrap:function(){this.parent().each(function(){k(this).replaceWith(k(this).children())});return this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(a){return this.each(function(){var c=k(this);
(a===t?"none"==c.css("display"):a)?c.show():c.hide()})},prev:function(a){return k(this.pluck("previousElementSibling")).filter(a||"*")},next:function(a){return k(this.pluck("nextElementSibling")).filter(a||"*")},html:function(a){return 0 in arguments?this.each(function(c){var d=this.innerHTML;k(this).empty().append(f(this,a,c,d))}):0 in this?this[0].innerHTML:null},text:function(a){return 0 in arguments?this.each(function(c){c=f(this,a,c,this.textContent);this.textContent=null==c?"":""+c}):0 in this?
this[0].textContent:null},attr:function(a,c){var d;return"string"==typeof a&&!(1 in arguments)?!this.length||1!==this[0].nodeType?t:!(d=this[0].getAttribute(a))&&a in this[0]?this[0][a]:d:this.each(function(d){if(1===this.nodeType)if(r(a))for(u in a){var p=u;d=a[u];null==d?this.removeAttribute(p):this.setAttribute(p,d)}else p=a,d=f(this,c,d,this.getAttribute(a)),null==d?this.removeAttribute(p):this.setAttribute(p,d)})},removeAttr:function(a){return this.each(function(){1===this.nodeType&&this.removeAttribute(a)})},
prop:function(a,c){a=Y[a]||a;return 1 in arguments?this.each(function(d){this[a]=f(this,c,d,this[a])}):this[0]&&this[0][a]},data:function(a,c){var d="data-"+a.replace(U,"-$1").toLowerCase(),d=1 in arguments?this.attr(d,c):this.attr(d);return null!==d?q(d):t},val:function(a){return 0 in arguments?this.each(function(c){this.value=f(this,a,c,this.value)}):this[0]&&(this[0].multiple?k(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value)},offset:function(a){if(a)return this.each(function(c){var d=
k(this);c=f(this,a,c,d.offset());var p=d.offsetParent().offset();c={top:c.top-p.top,left:c.left-p.left};"static"==d.css("position")&&(c.position="relative");d.css(c)});if(!this.length)return null;var c=this[0].getBoundingClientRect();return{left:c.left+window.pageXOffset,top:c.top+window.pageYOffset,width:Math.round(c.width),height:Math.round(c.height)}},css:function(c,d){if(2>arguments.length){var f=this[0],p=getComputedStyle(f,"");if(!f)return;if("string"==typeof c)return f.style[J(c)]||p.getPropertyValue(c);
if(H(c)){var e={};k.each(c,function(a,c){e[c]=f.style[J(c)]||p.getPropertyValue(c)});return e}}var h="";if("string"==a(c))!d&&0!==d?this.each(function(){this.style.removeProperty(n(c))}):h=n(c)+":"+("number"==typeof d&&!F[n(c)]?d+"px":d);else for(u in c)!c[u]&&0!==c[u]?this.each(function(){this.style.removeProperty(n(u))}):h+=n(u)+":"+("number"==typeof c[u]&&!F[n(u)]?c[u]+"px":c[u])+";";return this.each(function(){this.style.cssText+=";"+h})},index:function(a){return a?this.indexOf(k(a)[0]):this.parent().children().indexOf(this[0])},
hasClass:function(a){return!a?!1:D.some.call(this,function(a){return this.test(e(a))},x(a))},addClass:function(a){return!a?this:this.each(function(c){if("className"in this){E=[];var d=e(this);f(this,a,c,d).split(/\s+/g).forEach(function(a){k(this).hasClass(a)||E.push(a)},this);E.length&&e(this,d+(d?" ":"")+E.join(" "))}})},removeClass:function(a){return this.each(function(c){if("className"in this){if(a===t)return e(this,"");E=e(this);f(this,a,c,E).split(/\s+/g).forEach(function(a){E=E.replace(x(a),
" ")});e(this,E.trim())}})},toggleClass:function(a,c){return!a?this:this.each(function(d){var p=k(this);f(this,a,d,e(this)).split(/\s+/g).forEach(function(a){(c===t?!p.hasClass(a):c)?p.addClass(a):p.removeClass(a)})})},scrollTop:function(a){if(this.length){var c="scrollTop"in this[0];return a===t?c?this[0].scrollTop:this[0].pageYOffset:this.each(c?function(){this.scrollTop=a}:function(){this.scrollTo(this.scrollX,a)})}},scrollLeft:function(a){if(this.length){var c="scrollLeft"in this[0];return a===
t?c?this[0].scrollLeft:this[0].pageXOffset:this.each(c?function(){this.scrollLeft=a}:function(){this.scrollTo(a,this.scrollY)})}},position:function(){if(this.length){var a=this[0],c=this.offsetParent(),d=this.offset(),f=O.test(c[0].nodeName)?{top:0,left:0}:c.offset();d.top-=parseFloat(k(a).css("margin-top"))||0;d.left-=parseFloat(k(a).css("margin-left"))||0;f.top+=parseFloat(k(c[0]).css("border-top-width"))||0;f.left+=parseFloat(k(c[0]).css("border-left-width"))||0;return{top:d.top-f.top,left:d.left-
f.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||y.body;a&&!O.test(a.nodeName)&&"static"==k(a).css("position");)a=a.offsetParent;return a})}};k.fn.detach=k.fn.remove;["width","height"].forEach(function(a){var c=a.replace(/./,function(a){return a[0].toUpperCase()});k.fn[a]=function(d){var p,e=this[0];return d===t?l(e)?e["inner"+c]:s(e)?e.documentElement["scroll"+c]:(p=this.offset())&&p[a]:this.each(function(c){e=k(this);e.css(a,f(this,d,c,e[a]()))})}});["after",
"prepend","before","append"].forEach(function(c,d){var f=d%2;k.fn[c]=function(){var c,p=k.map(arguments,function(d){c=a(d);return"object"==c||"array"==c||null==d?d:A.fragment(d)}),e,h=1<this.length;return 1>p.length?this:this.each(function(a,c){e=f?c:c.parentNode;c=0==d?c.nextSibling:1==d?c.firstChild:2==d?c:null;var z=k.contains(y.documentElement,e);p.forEach(function(a){if(h)a=a.cloneNode(!0);else if(!e)return k(a).remove();e.insertBefore(a,c);z&&w(a,function(a){null!=a.nodeName&&"SCRIPT"===a.nodeName.toUpperCase()&&
((!a.type||"text/javascript"===a.type)&&!a.src)&&window.eval.call(window,a.innerHTML)})})})};k.fn[f?c+"To":"insert"+(d?"Before":"After")]=function(a){k(a)[c](this);return this}});A.Z.prototype=k.fn;A.uniq=K;A.deserializeValue=q;k.zepto=A;return k}();window.Zepto=Zepto;void 0===window.$&&(window.$=Zepto);
(function(a){"__proto__"in{}||a.extend(a.zepto,{Z:function(g,l){g=g||[];a.extend(g,a.fn);g.selector=l||"";g.__Z=!0;return g},isZ:function(g){return"array"===a.type(g)&&"__Z"in g}});try{getComputedStyle(void 0)}catch(g){var l=getComputedStyle;window.getComputedStyle=function(a){try{return l(a)}catch(g){return null}}}})(Zepto);
(function(a){function g(c){c=a(c);return!(!c.width()&&!c.height())&&"none"!==c.css("display")}function l(a,c){a=a.replace(/=#\]/g,'="#"]');var f,e,g=n.exec(a);g&&g[2]in v&&(f=v[g[2]],e=g[3],a=g[1],e&&(g=Number(e),e=isNaN(g)?e.replace(/^["']|["']$/g,""):g));return c(a,f,e)}var s=a.zepto,r=s.qsa,m=s.matches,v=a.expr[":"]={visible:function(){if(g(this))return this},hidden:function(){if(!g(this))return this},selected:function(){if(this.selected)return this},checked:function(){if(this.checked)return this},
parent:function(){return this.parentNode},first:function(a){if(0===a)return this},last:function(a,c){if(a===c.length-1)return this},eq:function(a,c,f){if(a===f)return this},contains:function(c,h,f){if(-1<a(this).text().indexOf(f))return this},has:function(a,c,f){if(s.qsa(this,f).length)return this}},n=/(.*):(\w+)(?:\(([^)]+)\))?$\s*/,x=/^\s*>/,c="Zepto"+ +new Date;s.qsa=function(d,h){return l(h,function(f,e,g){try{var m;!f&&e?f="*":x.test(f)&&(m=a(d).addClass(c),f="."+c+" "+f);var n=r(d,f)}catch(l){throw console.error("error performing selector: %o",
h),l;}finally{m&&m.removeClass(c)}return!e?n:s.uniq(a.map(n,function(a,c){return e.call(a,c,n,g)}))})};s.matches=function(a,c){return l(c,function(c,e,h){return(!c||m(a,c))&&(!e||e.call(a,null,h)===a)})}})(Zepto);
(function(a){a.fn.end=function(){return this.prevObject||a()};a.fn.andSelf=function(){return this.add(this.prevObject||a())};"filter add not eq first last find closest parents parent children siblings".split(" ").forEach(function(g){var l=a.fn[g];a.fn[g]=function(){var a=l.apply(this,arguments);a.prevObject=this;return a}})})(Zepto);
(function(a){function g(a){return a._zid||(a._zid=x++)}function l(a,c,d,f){c=s(c);if(c.ns)var h=RegExp("(?:^| )"+c.ns.replace(" "," .* ?")+"(?: |$)");return(e[g(a)]||[]).filter(function(a){return a&&(!c.e||a.e==c.e)&&(!c.ns||h.test(a.ns))&&(!d||g(a.fn)===g(d))&&(!f||a.sel==f)})}function s(a){a=(""+a).split(".");return{e:a[0],ns:a.slice(1).sort().join(" ")}}function r(d,f,p,h,k,m,n){var l=g(d),r=e[l]||(e[l]=[]);f.split(/\s/).forEach(function(f){if("ready"==f)return a(document).ready(p);var e=s(f);
e.fn=p;e.sel=k;e.e in u&&(p=function(c){var d=c.relatedTarget;if(!d||d!==this&&!a.contains(this,d))return e.fn.apply(this,arguments)});var g=(e.del=m)||p;e.proxy=function(a){a=v(a);if(!a.isImmediatePropagationStopped()){a.data=h;var f=g.apply(d,a._args==c?[a]:[a].concat(a._args));!1===f&&(a.preventDefault(),a.stopPropagation());return f}};e.i=r.length;r.push(e);"addEventListener"in d&&d.addEventListener(u[e.e]||w&&t[e.e]||e.e,e.proxy,e.del&&!w&&e.e in t||!!n)})}function m(a,c,d,f,h){var k=g(a);(c||
"").split(/\s/).forEach(function(c){l(a,c,d,f).forEach(function(c){delete e[k][c.i];"removeEventListener"in a&&a.removeEventListener(u[c.e]||w&&t[c.e]||c.e,c.proxy,c.del&&!w&&c.e in t||!!h)})})}function v(d,f){if(f||!d.isDefaultPrevented)if(f||(f=d),a.each(C,function(a,c){var e=f[a];d[a]=function(){this[c]=k;return e&&e.apply(f,arguments)};d[c]=E}),f.defaultPrevented!==c?f.defaultPrevented:"returnValue"in f?!1===f.returnValue:f.getPreventDefault&&f.getPreventDefault())d.isDefaultPrevented=k;return d}
function n(a){var d,f={originalEvent:a};for(d in a)!D.test(d)&&a[d]!==c&&(f[d]=a[d]);return v(f,a)}var x=1,c,d=Array.prototype.slice,h=a.isFunction,f=function(a){return"string"==typeof a},e={},q={},w="onfocusin"in window,t={focus:"focusin",blur:"focusout"},u={mouseenter:"mouseover",mouseleave:"mouseout"};q.click=q.mousedown=q.mouseup=q.mousemove="MouseEvents";a.event={add:r,remove:m};a.proxy=function(c,e){var p=2 in arguments&&d.call(arguments,2);if(h(c)){var z=function(){return c.apply(e,p?p.concat(d.call(arguments)):
arguments)};z._zid=g(c);return z}if(f(e))return p?(p.unshift(c[e],c),a.proxy.apply(null,p)):a.proxy(c[e],c);throw new TypeError("expected function");};a.fn.bind=function(a,c,d){return this.on(a,c,d)};a.fn.unbind=function(a,c){return this.off(a,c)};a.fn.one=function(a,c,d,f){return this.on(a,c,d,f,1)};var k=function(){return!0},E=function(){return!1},D=/^([A-Z]|returnValue$|layer[XY]$)/,C={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};
a.fn.delegate=function(a,c,d){return this.on(c,a,d)};a.fn.undelegate=function(a,c,d){return this.off(c,a,d)};a.fn.live=function(c,d){a(document.body).delegate(this.selector,c,d);return this};a.fn.die=function(c,d){a(document.body).undelegate(this.selector,c,d);return this};a.fn.on=function(e,g,p,z,k){var l,u,t=this;if(e&&!f(e))return a.each(e,function(a,c){t.on(a,g,p,c,k)}),t;!f(g)&&!h(z)&&!1!==z&&(z=p,p=g,g=c);if(h(p)||!1===p)z=p,p=c;!1===z&&(z=E);return t.each(function(c,f){k&&(l=function(a){m(f,
a.type,z);return z.apply(this,arguments)});g&&(u=function(c){var e,p=a(c.target).closest(g,f).get(0);if(p&&p!==f)return e=a.extend(n(c),{currentTarget:p,liveFired:f}),(l||z).apply(p,[e].concat(d.call(arguments,1)))});r(f,e,z,p,g,u||l)})};a.fn.off=function(d,e,p){var g=this;if(d&&!f(d))return a.each(d,function(a,c){g.off(a,e,c)}),g;!f(e)&&!h(p)&&!1!==p&&(p=e,e=c);!1===p&&(p=E);return g.each(function(){m(this,d,p,e)})};a.fn.trigger=function(c,d){c=f(c)||a.isPlainObject(c)?a.Event(c):v(c);c._args=d;
return this.each(function(){"dispatchEvent"in this?this.dispatchEvent(c):a(this).triggerHandler(c,d)})};a.fn.triggerHandler=function(c,d){var e,h;this.each(function(g,k){e=n(f(c)?a.Event(c):c);e._args=d;e.target=k;a.each(l(k,c.type||c),function(a,c){h=c.proxy(e);if(e.isImmediatePropagationStopped())return!1})});return h};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(c){a.fn[c]=
function(a){return a?this.bind(c,a):this.trigger(c)}});["focus","blur"].forEach(function(c){a.fn[c]=function(a){a?this.bind(c,a):this.each(function(){try{this[c]()}catch(a){}});return this}});a.Event=function(a,c){f(a)||(c=a,a=c.type);var d=document.createEvent(q[a]||"Events"),e=!0;if(c)for(var h in c)"bubbles"==h?e=!!c[h]:d[h]=c[h];d.initEvent(a,e,!0);return v(d)}})(Zepto);
(function(a){function g(c,d){var h=c[n],h=h&&r[h];if(void 0===d)return h||l(c);if(h){if(d in h)return h[d];var f=v(d);if(f in h)return h[f]}return m.call(a(c),d)}function l(c,d,h){var f=c[n]||(c[n]=++a.uuid);c=r[f]||(r[f]=s(c));void 0!==d&&(c[v(d)]=h);return c}function s(c){var d={};a.each(c.attributes||x,function(c,f){0==f.name.indexOf("data-")&&(d[v(f.name.replace("data-",""))]=a.zepto.deserializeValue(f.value))});return d}var r={},m=a.fn.data,v=a.camelCase,n=a.expando="Zepto"+ +new Date,x=[];a.fn.data=
function(c,d){return void 0===d?a.isPlainObject(c)?this.each(function(d,f){a.each(c,function(a,c){l(f,a,c)})}):0 in this?g(this[0],c):void 0:this.each(function(){l(this,c,d)})};a.fn.removeData=function(c){"string"==typeof c&&(c=c.split(/\s+/));return this.each(function(){var d=this[n],h=d&&r[d];h&&a.each(c||h,function(a){delete h[c?v(this):a]})})};["remove","empty"].forEach(function(c){var d=a.fn[c];a.fn[c]=function(){var a=this.find("*");"remove"===c&&(a=a.add(this));a.removeData();return d.call(this)}})})(Zepto);
(function(a){function g(c,d,f,e){if(c.global)return c=d||q,f=a.Event(f),a(c).trigger(f,e),!f.isDefaultPrevented()}function l(c){c.global&&0===a.active++&&g(c,null,"ajaxStart")}function s(a,c){var d=c.context;if(!1===c.beforeSend.call(d,a,c)||!1===g(c,d,"ajaxBeforeSend",[a,c]))return!1;g(c,d,"ajaxSend",[a,c])}function r(a,c,d,f){var e=d.context;d.success.call(e,a,"success",c);f&&f.resolveWith(e,[a,"success",c]);g(d,e,"ajaxSuccess",[c,d,a]);v("success",c,d)}function m(a,c,d,f,e){var h=f.context;f.error.call(h,
d,c,a);e&&e.rejectWith(h,[d,c,a]);g(f,h,"ajaxError",[d,f,a||c]);v(c,d,f)}function v(c,d,f){var e=f.context;f.complete.call(e,d,c);g(f,e,"ajaxComplete",[d,f]);f.global&&!--a.active&&g(f,null,"ajaxStop")}function n(){}function x(a){a&&(a=a.split(";",2)[0]);return a&&(a==C?"html":a==D?"json":k.test(a)?"script":E.test(a)&&"xml")||"text"}function c(a,c){return""==c?a:(a+"&"+c).replace(/[&?]{1,2}/,"?")}function d(d){d.processData&&d.data&&"string"!=a.type(d.data)&&(d.data=a.param(d.data,d.traditional));
if(d.data&&(!d.type||"GET"==d.type.toUpperCase()))d.url=c(d.url,d.data),d.data=void 0}function h(c,d,f,e){a.isFunction(d)&&(e=f,f=d,d=void 0);a.isFunction(f)||(e=f,f=void 0);return{url:c,data:d,success:f,dataType:e}}function f(c,d,e,h){var g,k=a.isArray(d),m=a.isPlainObject(d);a.each(d,function(d,n){g=a.type(n);h&&(d=e?h:h+"["+(m||"object"==g||"array"==g?d:"")+"]");!h&&k?c.add(n.name,n.value):"array"==g||!e&&"object"==g?f(c,n,e,d):c.add(d,n)})}var e=0,q=window.document,w,t,u=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
k=/^(?:text|application)\/javascript/i,E=/^(?:text|application)\/xml/i,D="application/json",C="text/html",B=/^\s*$/;a.active=0;a.ajaxJSONP=function(c,d){if(!("type"in c))return a.ajax(c);var f=c.jsonpCallback,h=(a.isFunction(f)?f():f)||"jsonp"+ ++e,g=q.createElement("script"),k=window[h],n,l=function(c){a(g).triggerHandler("error",c||"abort")},u={abort:l},t;d&&d.promise(u);a(g).on("load error",function(f,e){clearTimeout(t);a(g).off().remove();"error"==f.type||!n?m(null,e||"error",u,c,d):r(n[0],u,
c,d);window[h]=k;n&&a.isFunction(k)&&k(n[0]);k=n=void 0});if(!1===s(u,c))return l("abort"),u;window[h]=function(){n=arguments};g.src=c.url.replace(/\?(.+)=\?/,"?$1="+h);q.head.appendChild(g);0<c.timeout&&(t=setTimeout(function(){l("timeout")},c.timeout));return u};a.ajaxSettings={type:"GET",beforeSend:n,success:n,error:n,complete:n,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript, application/x-javascript",json:D,xml:"application/xml, text/xml",
html:C,text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};a.ajax=function(f){var e=a.extend({},f||{}),h=a.Deferred&&a.Deferred();for(w in a.ajaxSettings)void 0===e[w]&&(e[w]=a.ajaxSettings[w]);l(e);e.crossDomain||(e.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(e.url)&&RegExp.$2!=window.location.host);e.url||(e.url=window.location.toString());d(e);var g=e.dataType,k=/\?.+=\?/.test(e.url);k&&(g="jsonp");if(!1===e.cache||(!f||!0!==f.cache)&&("script"==g||"jsonp"==g))e.url=c(e.url,"_="+
Date.now());if("jsonp"==g)return k||(e.url=c(e.url,e.jsonp?e.jsonp+"=?":!1===e.jsonp?"":"callback=?")),a.ajaxJSONP(e,h);f=e.accepts[g];var u={},k=function(a,c){u[a.toLowerCase()]=[a,c]},v=/^([\w-]+:)\/\//.test(e.url)?RegExp.$1:window.location.protocol,q=e.xhr(),D=q.setRequestHeader,y;h&&h.promise(q);e.crossDomain||k("X-Requested-With","XMLHttpRequest");k("Accept",f||"*/*");if(f=e.mimeType||f)-1<f.indexOf(",")&&(f=f.split(",",2)[0]),q.overrideMimeType&&q.overrideMimeType(f);if(e.contentType||!1!==
e.contentType&&e.data&&"GET"!=e.type.toUpperCase())k("Content-Type",e.contentType||"application/x-www-form-urlencoded");if(e.headers)for(t in e.headers)k(t,e.headers[t]);q.setRequestHeader=k;q.onreadystatechange=function(){if(4==q.readyState){q.onreadystatechange=n;clearTimeout(y);var c,d=!1;if(200<=q.status&&300>q.status||304==q.status||0==q.status&&"file:"==v){g=g||x(e.mimeType||q.getResponseHeader("content-type"));c=q.responseText;try{"script"==g?(0,eval)(c):"xml"==g?c=q.responseXML:"json"==g&&
(c=B.test(c)?null:a.parseJSON(c))}catch(f){d=f}d?m(d,"parsererror",q,e,h):r(c,q,e,h)}else m(q.statusText||null,q.status?"error":"abort",q,e,h)}};if(!1===s(q,e))return q.abort(),m(null,"abort",q,e,h),q;if(e.xhrFields)for(t in e.xhrFields)q[t]=e.xhrFields[t];q.open(e.type,e.url,"async"in e?e.async:!0,e.username,e.password);for(t in u)D.apply(q,u[t]);0<e.timeout&&(y=setTimeout(function(){q.onreadystatechange=n;q.abort();m(null,"timeout",q,e,h)},e.timeout));q.send(e.data?e.data:null);return q};a.get=
function(){return a.ajax(h.apply(null,arguments))};a.post=function(){var c=h.apply(null,arguments);c.type="POST";return a.ajax(c)};a.getJSON=function(){var c=h.apply(null,arguments);c.dataType="json";return a.ajax(c)};a.fn.load=function(c,d,f){if(!this.length)return this;var e=this,g=c.split(/\s/),k;c=h(c,d,f);var n=c.success;1<g.length&&(c.url=g[0],k=g[1]);c.success=function(c){e.html(k?a("<div>").html(c.replace(u,"")).find(k):c);n&&n.apply(e,arguments)};a.ajax(c);return this};var y=encodeURIComponent;
a.param=function(a,c){var d=[];d.add=function(a,c){this.push(y(a)+"="+y(c))};f(d,a,c);return d.join("&").replace(/%20/g,"+")}})(Zepto);
(function(a){a.fn.serializeArray=function(){var g,l,s=[];a([].slice.call(this.get(0).elements)).each(function(){g=a(this);l=g.attr("type");this.name&&"fieldset"!=this.nodeName.toLowerCase()&&(!this.disabled&&"submit"!=l&&"reset"!=l&&"button"!=l&&("radio"!=l&&"checkbox"!=l||this.checked))&&s.push({name:g.attr("name"),value:g.val()})});return s};a.fn.serialize=function(){var a=[];this.serializeArray().forEach(function(l){a.push(encodeURIComponent(l.name)+"="+encodeURIComponent(l.value))});return a.join("&")};
a.fn.submit=function(g){g?this.bind("submit",g):this.length&&(g=a.Event("submit"),this.eq(0).trigger(g),g.isDefaultPrevented()||this.get(0).submit());return this}})(Zepto);
(function(a,g){var l="",s,r=window.document.createElement("div"),m=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i,v,n,x,c,d,h,f,e,q,w={};a.each({Webkit:"webkit",Moz:"",O:"o"},function(a,c){if(r.style[a+"TransitionProperty"]!==g)return l="-"+a.toLowerCase()+"-",s=c,!1});v=l+"transform";w[n=l+"transition-property"]=w[x=l+"transition-duration"]=w[d=l+"transition-delay"]=w[c=l+"transition-timing-function"]=w[h=l+"animation-name"]=w[f=l+"animation-duration"]=w[q=l+"animation-delay"]=
w[e=l+"animation-timing-function"]="";a.fx={off:s===g&&r.style.transitionProperty===g,speeds:{_default:400,fast:200,slow:600},cssPrefix:l,transitionEnd:s?s+"TransitionEnd":"transitionend",animationEnd:s?s+"AnimationEnd":"animationend"};a.fn.animate=function(c,d,f,e,h){a.isFunction(d)&&(e=d,d=f=g);a.isFunction(f)&&(e=f,f=g);a.isPlainObject(d)&&(f=d.easing,e=d.complete,h=d.delay,d=d.duration);d&&(d=("number"==typeof d?d:a.fx.speeds[d]||a.fx.speeds._default)/1E3);h&&(h=parseFloat(h)/1E3);return this.anim(c,
d,f,e,h)};a.fn.anim=function(l,u,k,r,s){var C,B={},y,p="",z=this,F,G=a.fx.transitionEnd,I=!1;u===g&&(u=a.fx.speeds._default/1E3);s===g&&(s=0);a.fx.off&&(u=0);if("string"==typeof l)B[h]=l,B[f]=u+"s",B[q]=s+"s",B[e]=k||"linear",G=a.fx.animationEnd;else{y=[];for(C in l)m.test(C)?p+=C+"("+l[C]+") ":(B[C]=l[C],y.push(C.replace(/([a-z])([A-Z])/,"$1-$2").toLowerCase()));p&&(B[v]=p,y.push(v));0<u&&"object"===typeof l&&(B[n]=y.join(", "),B[x]=u+"s",B[d]=s+"s",B[c]=k||"linear")}F=function(c){if("undefined"!==
typeof c){if(c.target!==c.currentTarget)return;a(c.target).unbind(G,F)}else a(this).unbind(G,F);I=!0;a(this).css(w);r&&r.call(this)};0<u&&(this.bind(G,F),setTimeout(function(){I||F.call(z)},1E3*u+25));this.size()&&this.get(0).clientLeft;this.css(B);0>=u&&setTimeout(function(){z.each(function(){F.call(this)})},0);return this};r=null})(Zepto);
(function(a,g){function l(n,l,c,d,h){"function"==typeof l&&!h&&(h=l,l=g);c={opacity:c};d&&(c.scale=d,n.css(a.fx.cssPrefix+"transform-origin","0 0"));return n.animate(c,l,null,h)}function s(g,r,c,d){return l(g,r,0,c,function(){m.call(a(this));d&&d.call(this)})}var r=a.fn.show,m=a.fn.hide,v=a.fn.toggle;a.fn.show=function(a,m){r.call(this);a===g?a=0:this.css("opacity",0);return l(this,a,1,"1,1",m)};a.fn.hide=function(a,l){return a===g?m.call(this):s(this,a,"0,0",l)};a.fn.toggle=function(l,m){return l===
g||"boolean"==typeof l?v.call(this,l):this.each(function(){var c=a(this);c["none"==c.css("display")?"show":"hide"](l,m)})};a.fn.fadeTo=function(a,g,c){return l(this,a,g,null,c)};a.fn.fadeIn=function(a,g){var c=this.css("opacity");0<c?this.css("opacity",0):c=1;return r.call(this).fadeTo(a,c,g)};a.fn.fadeOut=function(a,g){return s(this,a,null,g)};a.fn.fadeToggle=function(g,l){return this.each(function(){var c=a(this);c[0==c.css("opacity")||"none"==c.css("display")?"fadeIn":"fadeOut"](g,l)})}})(Zepto);
(function(a){function g(){c=null;m.last&&(m.el.trigger("longTap"),m={})}function l(){v&&clearTimeout(v);n&&clearTimeout(n);x&&clearTimeout(x);c&&clearTimeout(c);v=n=x=c=null;m={}}function s(a){return("touch"==a.pointerType||a.pointerType==a.MSPOINTER_TYPE_TOUCH)&&a.isPrimary}function r(a,c){return a.type=="pointer"+c||a.type.toLowerCase()=="mspointer"+c}var m={},v,n,x,c,d;a(document).ready(function(){var h,f,e=0,q=0,w,t;"MSGesture"in window&&(d=new MSGesture,d.target=document.body);a(document).bind("MSGestureEnd",
function(a){if(a=1<a.velocityX?"Right":-1>a.velocityX?"Left":1<a.velocityY?"Down":-1>a.velocityY?"Up":null)m.el.trigger("swipe"),m.el.trigger("swipe"+a)}).on("touchstart MSPointerDown pointerdown",function(e){if(!(t=r(e,"down"))||s(e))w=t?e:e.touches[0],e.touches&&1===e.touches.length&&m.x2&&(m.x2=void 0,m.y2=void 0),h=Date.now(),f=h-(m.last||h),m.el=a("tagName"in w.target?w.target:w.target.parentNode),v&&clearTimeout(v),m.x1=w.pageX,m.y1=w.pageY,0<f&&250>=f&&(m.isDoubleTap=!0),m.last=h,c=setTimeout(g,
750),d&&t&&d.addPointer(e.pointerId)}).on("touchmove MSPointerMove pointermove",function(a){if(!(t=r(a,"move"))||s(a))w=t?a:a.touches[0],c&&clearTimeout(c),c=null,m.x2=w.pageX,m.y2=w.pageY,e+=Math.abs(m.x1-m.x2),q+=Math.abs(m.y1-m.y2)}).on("touchend MSPointerUp pointerup",function(d){if(!(t=r(d,"up"))||s(d))c&&clearTimeout(c),c=null,m.x2&&30<Math.abs(m.x1-m.x2)||m.y2&&30<Math.abs(m.y1-m.y2)?x=setTimeout(function(){m.el.trigger("swipe");m.el.trigger("swipe"+(Math.abs(m.x1-m.x2)>=Math.abs(m.y1-m.y2)?
0<m.x1-m.x2?"Left":"Right":0<m.y1-m.y2?"Up":"Down"));m={}},0):"last"in m&&(30>e&&30>q?n=setTimeout(function(){var c=a.Event("tap");c.cancelTouch=l;m.el.trigger(c);m.isDoubleTap?(m.el&&m.el.trigger("doubleTap"),m={}):v=setTimeout(function(){v=null;m.el&&m.el.trigger("singleTap");m={}},250)},0):m={}),e=q=0}).on("touchcancel MSPointerCancel pointercancel",l);a(window).on("scroll",l)});"swipe swipeLeft swipeRight swipeUp swipeDown doubleTap tap singleTap longTap".split(" ").forEach(function(c){a.fn[c]=
function(a){return this.on(c,a)}})})(Zepto);(function(a,g){var l=window.KingSoft=window.K||{},s=document.createElement("div").style,r={};window.K=l;l.supports=l.supports||r;var m=l.camelCase=function(a){return a.replace(/^-ms-/,"ms-").replace(/-([a-z]|[0-9])/ig,function(a,c){return(c+"").toUpperCase()})};l.uncamelCase=function(a){return a.replace(/([A-Z]|^ms)/g,"-$1").toLowerCase()};var v=l.cssVendor=function(){var a=["-webkit-","-moz-","-ms-",""],d=0;do if(m(a[d]+"transform")in s)return a[d];while(++d<a.length);return""}();l.transitionend=
{"-webkit-":"webkitTransitionEnd","-moz-":"transitionend","-ms-":"MSTransitionEnd","":"transitionend"}[v];var n=l.isCSS=function(a){var d=m(a);a=m(v+a);return d in s&&d||a in s&&a||""};l.isArrayLike=function(a){var d=l.type(a);return!!a&&"function"!=d&&"string"!=d&&(0===a.length||a.length&&a.length-1 in a)};var x=l.type=function(){for(var a="Boolean Number String Function Array Date RegExp Object Error Undefined Null".split(" "),d=0,g={};d<a.length;)l["is"+a[d]]=function(){var f=a[d].toLowerCase();
return function(a){return x(a)===f}}(),g["[object "+a[d]+"]"]=a[d++].toLowerCase();return function(a){return null==a?String(a):"object"==typeof a?g[g.toString.call(a)]||"object":typeof a}}();l.getQueryValue=function(a,d){var g=decodeURIComponent(d||location.search).match(RegExp(a+"=([^&]*)"));return g&&g[1]||""};l.getAbsUrl=function(a){var d=document.createElement("a");d.href=a;return/^http/i.test(d.href)?d.href:d.getAttribute("href",4)};l.htmlencode=function(a){return String(a).replace(/&(?![\w#]+;)|[<>"']/g,
function(a){return{"<":"&#60;",">":"&#62;",'"':"&#34;","'":"&#39;","&":"&#38;"}[a]||""})};a.each("transform transition animation perspective border-image border-radius box-shadow background-size background-clip text-shadow min-height opacity".split(" "),function(a,d){r[m(d)]=!!n(d)});r.touch="createTouch"in document||"ontouchstart"in window;r.canvas="function"==typeof document.createElement("canvas").getContext;r.svg=!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg",
"svg").createSVGRect;l.transform=n("transform");l.transition=n("transition");l.animation=n("animation");l.EVENTS="PointerEvent"in window?"pointerdown pointermove pointerup pointercancel":r.touch?"touchstart touchmove touchend touchcancel":"mousedown mousemove mouseup";r.touch||a(document).click(function(c){var d=a.Event("tap");a(c.target||c.srcElement).trigger(d)});l.Panel=createClass(function(){this.zIndex=this.constructor.prototype.zIndex++;this.mask=a('<div class="Mask" style="z-index:'+this.zIndex+
';"></div>');this.frame=a('<div class="Panel" style="z-index:'+this.zIndex+';"></div>')},{zIndex:100,setContent:function(a){this.frame.html(a);return this},show:function(c){a.contains(document.body,this.frame[0])||(this.mask.appendTo("body"),this.frame.appendTo("body"));this.frame.fadeIn(400,c);this.mask.fadeIn(400);return this},hide:function(a){this.frame.fadeOut(400,a);this.mask.fadeOut(400);return this},destroy:function(a){this.hide(function(){this.frame.remove();this.mask.remove();a&&a()}.bind(this))}});
a.ajaxSettings.cache=!1;a.ajaxSettings.dataType="json";a.ajaxSettings.type="POST";l.alert=function(a){var d=l.Panel().setContent('<a class="close"></a><div class="text">'+a+"</div>");d.frame.addClass("syswin").find(".close").tap(function(){d.destroy()});d.mask.tap(function(){d.destroy()});d.show()};a(document).on("click","[trace]",function(c){var d=this.nodeName.toLowerCase(),g=a(this),f=g.attr("trace").split(/,\s*/g),e=this.href||"";_hmt.push(["_trackEvent"].concat(f,1));"a"==d&&("_blank"!=g.attr("target")&&
e&&!/^javascript/i.test(e))&&setTimeout(function(){location.href=e},150);c.preventDefault()});Share.init({gzh:"liebao_zhushou"}).update({title:"\u55e8\uff0c2015\u4f60\u60f3\u8981\u4ec0\u4e48\u793c\u7269",desc:"\u55e8\uff0c2015\u4f60\u60f3\u8981\u4ec0\u4e48\u793c\u7269\uff0c\u753b\u4ec0\u4e48\u6709\u4ec0\u4e48\u54e6\uff0c\u65b0\u5e74\u793c\u7269\u7b49\u4f60\u62ff~",success:function(a){location.href="http://mp.weixin.qq.com/s?__biz=MjM5ODY4NTQwNA==&mid=204592543&idx=1&sn=b0b52ae3233bfbfbd64be1f5f97d4611#rd"},
img:l.getAbsUrl("images/wx.jpg"),url:l.getAbsUrl("./")})})(Zepto);
